// Temporary registrations that reproduce today's behavior, one file per
// future owning module. Each module plan deletes its file and registers the
// same hooks from its manifest (setting moduleId and security/alwaysRun).
// Delete this folder when it is empty.
import "./advanced-permissions.js"
import "./agent-mcp.js"
import "./ai-gateway.js"
import "./analytics.js"
import "./audit-logs.js"
import "./automations.js"
import "./billing.js"
import "./branding.js"
import "./connect.js"
import "./connect-native-providers.js"
import "./custom-providers.js"
import "./dashboards.js"
import "./desktop-policies.js"
import "./diagnostics.js"
import "./enterprise-auth-scim.js"
import "./enterprise-auth-sso.js"
import "./free-inference.js"
import "./install-links.js"
import "./marketplace.js"
import "./marketplace-github-sync.js"
import "./open-work-models.js"
import "./open-work-web.js"
import "./remote-sessions.js"
import "./retired-generated-views.js"
import "./slack-assistant.js"
import "./teams.js"
import "./web-origins.js"
import "./workbot.js"
import "./workflows.js"
import "./workspace-bootstrap.js"
