const orgBasePath = "/v1"

export const githubSyncRoutePaths = {
  connectorAccounts: `${orgBasePath}/connector-accounts`,
  connectorAccount: `${orgBasePath}/connector-accounts/:connectorAccountId`,
  connectorAccountDisconnect: `${orgBasePath}/connector-accounts/:connectorAccountId/disconnect`,
  connectorInstances: `${orgBasePath}/connector-instances`,
  connectorInstance: `${orgBasePath}/connector-instances/:connectorInstanceId`,
  connectorInstanceConfiguration: `${orgBasePath}/connector-instances/:connectorInstanceId/configuration`,
  connectorInstanceAutoImport: `${orgBasePath}/connector-instances/:connectorInstanceId/auto-import`,
  connectorInstanceRemove: `${orgBasePath}/connector-instances/:connectorInstanceId/remove`,
  connectorInstanceArchive: `${orgBasePath}/connector-instances/:connectorInstanceId/archive`,
  connectorInstanceDisable: `${orgBasePath}/connector-instances/:connectorInstanceId/disable`,
  connectorInstanceEnable: `${orgBasePath}/connector-instances/:connectorInstanceId/enable`,
  connectorInstanceSyncNow: `${orgBasePath}/connector-instances/:connectorInstanceId/sync-now`,
  connectorInstanceAccess: `${orgBasePath}/connector-instances/:connectorInstanceId/access`,
  connectorInstanceAccessGrant: `${orgBasePath}/connector-instances/:connectorInstanceId/access/:grantId`,
  connectorTargets: `${orgBasePath}/connector-instances/:connectorInstanceId/targets`,
  connectorTarget: `${orgBasePath}/connector-targets/:connectorTargetId`,
  connectorTargetResync: `${orgBasePath}/connector-targets/:connectorTargetId/resync`,
  connectorTargetMappings: `${orgBasePath}/connector-targets/:connectorTargetId/mappings`,
  connectorMapping: `${orgBasePath}/connector-mappings/:connectorMappingId`,
  connectorMappingPreview: `${orgBasePath}/connector-mappings/:connectorMappingId/preview`,
  connectorSyncEvents: `${orgBasePath}/connector-sync-events`,
  connectorSyncEvent: `${orgBasePath}/connector-sync-events/:connectorSyncEventId`,
  connectorSyncEventRetry: `${orgBasePath}/connector-sync-events/:connectorSyncEventId/retry`,
  connectorInstanceDiscovery: `${orgBasePath}/connector-instances/:connectorInstanceId/discovery`,
  connectorInstanceDiscoveryApply: `${orgBasePath}/connector-instances/:connectorInstanceId/discovery/apply`,
  connectorInstanceDiscoveryTree: `${orgBasePath}/connector-instances/:connectorInstanceId/discovery/tree`,
  githubInstallStart: `${orgBasePath}/connectors/github/install/start`,
  githubInstallComplete: `${orgBasePath}/connectors/github/install/complete`,
  githubSetup: `${orgBasePath}/connectors/github/setup`,
  githubAccounts: `${orgBasePath}/connectors/github/accounts`,
  githubAccountRepositories: `${orgBasePath}/connectors/github/accounts/:connectorAccountId/repositories`,
  githubValidateTarget: `${orgBasePath}/connectors/github/validate-target`,
  githubWebhookIngress: "/v1/webhooks/connectors/github",
} as const
