export const adminHTML = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OpenWork Remote · Computer setup</title><link rel="stylesheet" href="/admin.css"><script defer src="/admin.js"></script></head><body><main><div class="mark">↗</div><p class="eyebrow">OPENWORK REMOTE</p><h1>Your computer.<br>Within reach.</h1><p>Pair your iPhone, then choose the workspaces it can access.</p><div id="status" role="status">Connecting to OpenWork…</div><button id="reload" hidden>Reload setup</button><section><h2>Pair a phone</h2><p>Connect both devices to Tailscale. Open OpenWork Remote on your phone and scan the code. Codes expire after five minutes.</p><button id="pair">Create pairing code</button><div id="qr"></div><button id="copy" hidden>Copy pairing payload</button><p id="copy-status" role="status"></p></section><section><h2>Confirm your phone</h2><div id="pending">No phone waiting.</div></section><section><h2>Paired phones</h2><div id="devices">No paired phones.</div></section><p class="foot">OpenWork keeps your models, tools and chats on this computer. This setup page stays local.</p></main></body></html>`;
export const adminCSS = `:root{font:16px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#202124;background:#f7f6f2}body{margin:0;padding:36px 20px}main{max-width:620px;margin:auto}h1{font-size:48px;letter-spacing:-2px;line-height:1.06;margin:14px 0 20px}h2{font-size:22px}p{line-height:1.6;color:#61636b}.mark{width:48px;height:48px;border-radius:16px;color:white;background:#335bdf;display:grid;place-items:center;font-size:30px}.eyebrow{font-size:12px;letter-spacing:2px;font-weight:700}section{background:white;border:1px solid #e5e4df;border-radius:22px;padding:24px;margin:22px 0}button{min-height:44px;border:0;border-radius:14px;background:#335bdf;color:white;padding:10px 18px;font:600 15px inherit;cursor:pointer;margin:4px 8px 4px 0}button.secondary{background:#ececf2;color:#202124}button:disabled{opacity:.5;cursor:default}label{display:flex;align-items:center;gap:8px;margin:10px 0;min-height:44px}input{width:20px;height:20px}#qr{max-width:260px;margin:20px auto}#qr svg{display:block;width:100%}.foot{font-size:13px}#status{padding:12px 0;font-weight:600}@media(prefers-color-scheme:dark){:root{color:#f0f0f2;background:#141519}section{background:#202126;border-color:#34353d}p{color:#adafb9}button.secondary{background:#34353d;color:#f0f0f2}}`;
export const adminJS = String.raw`let csrf='',payload=null,refreshTimer;
const selections=new Map(),openPanels=new Set();
const el=id=>document.getElementById(id);
async function request(path,body){
 const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-Admin-Session':csrf},body:body===undefined?undefined:JSON.stringify(body)}),j=await r.json();
 if(!r.ok){if(r.status===403){clearInterval(refreshTimer);csrf='';payload=null;el('qr').replaceChildren();el('copy').hidden=true;el('pair').disabled=true;el('pending').replaceChildren();el('devices').replaceChildren();el('reload').hidden=false;throw Error('This setup session expired. Reload setup to continue.')}throw Error(j.error.message)}return j.data;
}
function button(text,action,secondary=false){const b=document.createElement('button');b.textContent=text;if(secondary)b.className='secondary';b.onclick=async()=>{b.disabled=true;try{await action();await refresh()}catch(e){el('status').textContent=e.message}finally{b.disabled=false}};return b}
function accessFields(key,workspaces,initial={workspaceIds:[],allWorkspaces:false}){
 if(!selections.has(key))selections.set(key,{selected:new Set(initial.workspaceIds),all:initial.allWorkspaces});const value=selections.get(key),box=document.createElement('div');
 const label=document.createElement('label'),all=document.createElement('input');all.type='checkbox';all.checked=value.all;label.append(all,document.createTextNode('Allow all future projects'));box.append(label);
 const help=document.createElement('p');help.textContent='Includes all current projects and projects added later.';box.append(help);
 const inputs=[];for(const w of workspaces){const row=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=value.all||value.selected.has(w.id);check.disabled=value.all;check.onchange=()=>check.checked?value.selected.add(w.id):value.selected.delete(w.id);row.append(check,document.createTextNode(w.name));box.append(row);inputs.push({check,id:w.id})}
 all.onchange=()=>{value.all=all.checked;for(const {check,id} of inputs){check.disabled=value.all;check.checked=value.all||value.selected.has(id)}};
 return {box,body:()=>({workspaceIds:[...value.selected].filter(id=>workspaces.some(w=>w.id===id)),allWorkspaces:value.all})};
}
async function refresh(){try{
 const s=await request('/admin/state');csrf=s.csrf;el('status').textContent=s.host.compatibility==='supported'?'OpenWork connected · '+s.host.upstreamVersion:'Check your OpenWork version';
 el('pending').replaceChildren();if(!s.pending.length)el('pending').textContent='No phone waiting.';
 for(const c of s.pending){const box=document.createElement('div'),name=document.createElement('h3');name.textContent=c.deviceName;box.append(name);const fields=accessFields('claim:'+c.id,s.workspaces);box.append(fields.box,button('Allow access',()=>request('/admin/claims/'+encodeURIComponent(c.id)+'/approve',fields.body())),button('Deny',()=>request('/admin/claims/'+encodeURIComponent(c.id)+'/deny',{}),true));el('pending').append(box)}
 el('devices').replaceChildren();if(!s.devices.length)el('devices').textContent='No paired phones.';
 for(const d of s.devices){const box=document.createElement('div'),name=document.createElement('p'),scope=document.createElement('p');name.textContent=d.name+(d.active?' · Paired':' · Waiting for phone');scope.textContent=d.allWorkspaces?'All current and future projects':d.workspaceIds.length+' selected projects';box.append(name,scope);
 if(d.active){box.append(button('Project access',async()=>{openPanels.has(d.id)?openPanels.delete(d.id):openPanels.add(d.id)},true));if(openPanels.has(d.id)){const fields=accessFields('device:'+d.id,s.workspaces,d);box.append(fields.box,button('Save project access',async()=>{await request('/admin/devices/'+encodeURIComponent(d.id)+'/access',fields.body());selections.delete('device:'+d.id);openPanels.delete(d.id)}));}}
 box.append(button('Revoke phone',()=>request('/admin/devices/'+encodeURIComponent(d.id)+'/revoke',{}),true));el('devices').append(box);
 }
 }catch(e){el('status').textContent=e.message}}
el('pair').onclick=async()=>{try{const p=await request('/admin/pairings',{});payload=JSON.stringify(p.payload);el('qr').innerHTML=p.qrSvg;el('copy').hidden=false;el('copy-status').textContent='Ready to scan. Confirm the phone below.'}catch(e){el('status').textContent=e.message}};
el('copy').onclick=async()=>{try{await navigator.clipboard.writeText(payload);el('copy-status').textContent='Copied. Paste in OpenWork Remote.'}catch{el('copy-status').textContent='Clipboard unavailable. Use the QR code.'}};
el('reload').onclick=()=>location.reload();refreshTimer=setInterval(refresh,2500);refresh();
`;
