import { defineConfig } from "tsup"

export default defineConfig({
  entry: {
    index: "src/index.ts",
    "den-urls": "src/den-urls.ts",
    "inference-bearer-key": "src/inference-bearer-key.ts",
    "free-inference-digest": "src/free-inference-digest.ts",
    "gateway-bearer-key": "src/gateway-bearer-key.ts",
    "gateway-routing": "src/gateway-routing.ts",
    "gateway-env": "src/gateway-env.ts",
    "gateway-rollups": "src/gateway-rollups.ts",
    "inference-egress": "src/inference-egress.ts",
    "inference-credentials": "src/inference-credentials.ts",
    "bedrock-mantle-catalog": "src/bedrock-mantle-catalog.ts",
    "ai-sdk-env-settings": "src/ai-sdk-env-settings.ts",
    "litellm-catalog": "src/litellm-catalog.ts",
    "aws-sigv4": "src/aws-sigv4.ts",
    "aws-identity-center": "src/aws-identity-center.ts",
    "microsoft-entra": "src/microsoft-entra.ts",
    "microsoft-foundry-catalog": "src/microsoft-foundry-catalog.ts",
    observability: "src/observability.ts",
    typeid: "src/typeid.ts",
  },
  format: ["esm"],
  dts: false,
  clean: true,
  target: "es2022",
  platform: "node",
  sourcemap: false,
  splitting: false,
  treeshake: true,
})
