import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import {
  DESKTOP_FREE_PROVIDER_ID, DESKTOP_FREE_MODEL_ID, DESKTOP_FREE_PROOF_HEADER,
  DESKTOP_FREE_SESSION_PATH, DESKTOP_FREE_STATUS_PATH, DESKTOP_FREE_MODELS_PATH,
  DESKTOP_FREE_CHAT_PATH, type DesktopFreeAccessStatus, type DesktopFreeSession,
} from "@openwork/types/desktop-free-access";
import type { ManagedModelRecommendation } from "@openwork/types/den/inference";
import type { ServerConfig } from "./types.js";
import { ApiError } from "./errors.js";
import { externalFetch } from "./server-fetch.js";
import {
  mergeRuntimeProviderUpdate, readGlobalRuntimeOpencodeConfig,
  runtimeDisabledProviderList, writeGlobalRuntimeOpencodeConfig,
} from "./runtime-opencode-config-store.js";

export const ANONYMOUS_INFERENCE_PROVIDER_ID = DESKTOP_FREE_PROVIDER_ID;
export const ANONYMOUS_INFERENCE_MODEL_ID = DESKTOP_FREE_MODEL_ID;
export const ANONYMOUS_INFERENCE_PROVIDER_NAME = "OpenWork Models (Free)";
const LOCAL_ROUTE_PREFIX = "/anonymous-inference/v1";
const REQUEST_BODY_LIMIT = 2 * 1024 * 1024;
const ERROR_BODY_LIMIT = 64 * 1024;
const SESSION_TIMEOUT_MS = 10_000;
const REQUEST_LIFETIME_MS = 5 * 60_000;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isRecommendation(value: unknown): value is ManagedModelRecommendation {
  return isRecord(value) && typeof value.modelID === "string" && typeof value.displayName === "string"
    && typeof value.providerName === "string" && typeof value.summary === "string"
    && typeof value.recommended === "boolean" && typeof value.rank === "number" && Number.isFinite(value.rank)
    && Array.isArray(value.capabilities) && value.capabilities.every((capability) => typeof capability === "string");
}

export function resolveAnonymousInferenceOrigin(environment: NodeJS.ProcessEnv = process.env): string {
  const url = new URL(environment.OPENWORK_FREE_INFERENCE_ORIGIN?.trim() || "https://inference.openworklabs.com");
  const local = (environment.OPENWORK_DEV_MODE === "1" || environment.NODE_ENV === "test")
    && ["localhost", "127.0.0.1", "[::1]"].includes(url.hostname);
  if (url.username || url.password || url.search || url.hash || url.pathname !== "/"
    || (url.protocol !== "https:" && !(local && url.protocol === "http:"))) {
    throw new Error("OPENWORK_FREE_INFERENCE_ORIGIN must be an HTTPS origin (loopback HTTP is development-only).");
  }
  return url.origin;
}

function hasExactKeys(value: Record<string, unknown>, expected: string[]): boolean {
  return Object.keys(value).length === expected.length && expected.every((key) => Object.hasOwn(value, key));
}

function generatedModel(id = ANONYMOUS_INFERENCE_MODEL_ID) {
  return {
    id, name: "GPT-5.6 Luna", attachment: false, reasoning: false, temperature: false, tool_call: true,
    options: { reasoningEffort: "none" },
    limit: { context: 135_168, input: 131_072, output: 4_096 },
    modalities: { input: ["text"], output: ["text"] },
  };
}

// The exact shapes generated by #4621 only. User additions/edits are not ours
// to overwrite or remove, even when they occupy the reserved provider id.
export function isOwnedProvider(value: unknown): boolean {
  if (!isRecord(value) || !hasExactKeys(value, ["name", "npm", "options", "models"])
    || value.name !== ANONYMOUS_INFERENCE_PROVIDER_NAME || value.npm !== "@openrouter/ai-sdk-provider"
    || !isRecord(value.options) || !hasExactKeys(value.options, ["apiKey", "baseURL"])
    || typeof value.options.apiKey !== "string" || !/^owf_local_[A-Za-z0-9_-]{43}$/.test(value.options.apiKey)
    || typeof value.options.baseURL !== "string" || !/^http:\/\/127\.0\.0\.1:\d+\/anonymous-inference\/v1$/.test(value.options.baseURL)
    || !isRecord(value.models) || Object.keys(value.models).length !== 1) return false;
  const id = Object.keys(value.models)[0];
  if (id !== ANONYMOUS_INFERENCE_MODEL_ID && id !== "deepseek/deepseek-v4-flash") return false;
  const model = value.models[id];
  if (!isRecord(model)) return false;
  const keys = ["id", "name", "attachment", "reasoning", "temperature", "tool_call", "limit", "modalities"];
  const fixedOptions = hasExactKeys(model, [...keys, "options"]);
  if (!hasExactKeys(model, keys) && !fixedOptions) return false;
  if (model.id !== id || model.name !== (id === ANONYMOUS_INFERENCE_MODEL_ID ? "GPT-5.6 Luna" : "DeepSeek V4 Flash")
    || model.attachment !== false || model.reasoning !== false
    || model.temperature !== (id !== ANONYMOUS_INFERENCE_MODEL_ID) || model.tool_call !== true
    || !isRecord(model.limit) || !hasExactKeys(model.limit, ["context", "input", "output"])
    || model.limit.context !== 135_168 || model.limit.input !== 131_072 || model.limit.output !== 4_096
    || !isRecord(model.modalities) || !hasExactKeys(model.modalities, ["input", "output"])
    || !Array.isArray(model.modalities.input) || model.modalities.input.length !== 1 || model.modalities.input[0] !== "text"
    || !Array.isArray(model.modalities.output) || model.modalities.output.length !== 1 || model.modalities.output[0] !== "text") return false;
  return !fixedOptions || (id === ANONYMOUS_INFERENCE_MODEL_ID && isRecord(model.options)
    && hasExactKeys(model.options, ["reasoningEffort"]) && model.options.reasoningEffort === "none");
}

function jsonError(status: number, code: string, message: string): Response {
  return Response.json({ error: { message, type: "openwork_anonymous_error", code } }, { status });
}

function responseHeaders(headers: Headers): Headers {
  const result = new Headers();
  for (const name of ["content-type", "retry-after", "x-request-id", "x-openwork-anonymous-no-upstream-retry"]) {
    const value = headers.get(name);
    if (value) result.set(name, value);
  }
  return result;
}

async function readBoundedBody(stream: ReadableStream<Uint8Array> | null, limit: number, signal: AbortSignal): Promise<Uint8Array<ArrayBuffer>> {
  signal.throwIfAborted();
  if (!stream) return new Uint8Array();
  const reader = stream.getReader();
  const chunks: Uint8Array[] = [];
  let length = 0;
  const abort = () => { void reader.cancel(signal.reason).catch(() => undefined); };
  signal.addEventListener("abort", abort, { once: true });
  try {
    while (true) {
      signal.throwIfAborted();
      const chunk = await reader.read();
      signal.throwIfAborted();
      if (chunk.done) break;
      length += chunk.value.byteLength;
      if (length > limit) throw new ApiError(413, "anonymous_request_too_large", "The OpenWork Models request is too large.");
      chunks.push(chunk.value);
    }
  } catch (error) {
    void reader.cancel(error).catch(() => undefined);
    throw error;
  } finally { signal.removeEventListener("abort", abort); }
  const body = new Uint8Array(length);
  let offset = 0;
  for (const chunk of chunks) { body.set(chunk, offset); offset += chunk.byteLength; }
  return body;
}

class RemoteFailure extends Error {
  constructor(readonly status: number, readonly body: Uint8Array<ArrayBuffer>, readonly headers: Headers) {
    super("Desktop free inference gateway rejected the request.");
  }
  response() { return new Response(this.body.slice(), { status: this.status, headers: this.headers }); }
  payload(): Record<string, unknown> {
    try {
      const parsed: unknown = JSON.parse(new TextDecoder().decode(this.body));
      if (isRecord(parsed)) {
        if (isRecord(parsed.error)) return { ...parsed, ...parsed.error, ...(isRecord(parsed.error.details) ? parsed.error.details : {}) };
        return { ...parsed, ...(isRecord(parsed.details) ? parsed.details : {}) };
      }
    } catch { /* Invalid gateway errors fail closed without logging remote bytes. */ }
    return {};
  }
}

export class AnonymousInferenceService {
  private readonly origin: string;
  private readonly localAccessToken = `owf_local_${randomBytes(32).toString("base64url")}`;
  private readonly enabled: boolean;
  private available = false;
  private stopped = false;
  private session: DesktopFreeSession | null = null;
  private sessionPromise: Promise<DesktopFreeSession> | null = null;
  private activeControllers = new Set<AbortController>();
  private failures = new Map<string, { expiresAt: number; failure: RemoteFailure }>();
  private cachedStatus: { expiresAt: number; value: DesktopFreeAccessStatus } | null = null;

  constructor(private readonly config: ServerConfig, private readonly logger: {
    log: (level: "info" | "warn" | "error", message: string, attributes?: Record<string, unknown>) => void;
  }, environment: NodeJS.ProcessEnv = process.env) {
    this.origin = resolveAnonymousInferenceOrigin(environment);
    this.enabled = Boolean(config.anonymousInference?.desktop)
      && !config.readOnly
      && ![environment.OPENWORK_DISABLE_FREE_INFERENCE, environment.OPENWORK_DISABLE_HOSTED_MODELS, environment.VITE_DISABLE_OPENWORK_MODELS]
        .some((value) => /^(?:1|true|yes|on)$/i.test(value?.trim() ?? ""));
  }

  async initialize(boundPort: number): Promise<boolean> {
    this.cachedStatus = null;
    if (this.stopped || this.config.readOnly) return false;
    // Policy is deliberately omitted from the editable writer snapshot.
    const runtime = await readGlobalRuntimeOpencodeConfig(this.config);
    let permitted = this.enabled && runtime.managedPolicy?.allowCustomProviders !== false;
    if (permitted) {
      try { await this.config.anonymousInference!.desktop.identity(); }
      catch { permitted = false; }
    }
    let changed = false;
    await writeGlobalRuntimeOpencodeConfig(this.config, (snapshot) => {
      const current = snapshot.provider?.[ANONYMOUS_INFERENCE_PROVIDER_ID];
      permitted = permitted && !runtimeDisabledProviderList(snapshot).includes(ANONYMOUS_INFERENCE_PROVIDER_ID);
      if (!permitted || (current !== undefined && !isOwnedProvider(current))) {
        this.disable();
        if (!isOwnedProvider(current)) return snapshot;
        changed = true;
        return { ...snapshot, provider: mergeRuntimeProviderUpdate(snapshot.provider, { [ANONYMOUS_INFERENCE_PROVIDER_ID]: null }) };
      }
      this.available = true;
      const provider = {
        name: ANONYMOUS_INFERENCE_PROVIDER_NAME, npm: "@openrouter/ai-sdk-provider",
        options: { apiKey: this.localAccessToken, baseURL: `http://127.0.0.1:${boundPort}${LOCAL_ROUTE_PREFIX}` },
        models: { [ANONYMOUS_INFERENCE_MODEL_ID]: generatedModel() },
      };
      changed = JSON.stringify(current) !== JSON.stringify(provider);
      return changed ? { ...snapshot, provider: mergeRuntimeProviderUpdate(snapshot.provider, { [ANONYMOUS_INFERENCE_PROVIDER_ID]: provider }) } : snapshot;
    });
    return changed;
  }

  private unavailable(code = "anonymous_unavailable"): DesktopFreeAccessStatus {
    return {
      state: "unavailable", code, currentVersion: this.config.anonymousInference?.desktop.currentVersion ?? "",
      minimumVersion: null, providerID: DESKTOP_FREE_PROVIDER_ID, modelID: DESKTOP_FREE_MODEL_ID, allowance: null,
    };
  }

  private async assertDispatchAllowed(): Promise<void> {
    if (!this.enabled || !this.available || this.stopped) throw new Error("Desktop free inference is unavailable.");
    const runtime = await readGlobalRuntimeOpencodeConfig(this.config);
    const provider = runtime.provider?.[ANONYMOUS_INFERENCE_PROVIDER_ID];
    if (runtime.managedPolicy?.allowCustomProviders === false || runtimeDisabledProviderList(runtime).includes(ANONYMOUS_INFERENCE_PROVIDER_ID)
      || !isOwnedProvider(provider) || !isRecord(provider) || !isRecord(provider.options) || provider.options.apiKey !== this.localAccessToken) {
      this.disable();
      throw new Error("Desktop free inference is disabled by local policy or configuration.");
    }
    await this.config.anonymousInference!.desktop.identity();
  }

  /** Authenticated local status/preflight callers get no bearer or key material. */
  async status(force = false): Promise<DesktopFreeAccessStatus> {
    try {
      await this.assertDispatchAllowed();
      if (!force && this.cachedStatus && this.cachedStatus.expiresAt > Date.now()) return this.cachedStatus.value;
      if (force) this.failures.clear();
      const response = await this.remote(DESKTOP_FREE_STATUS_PATH, "GET", new Uint8Array(), true);
      const payload: unknown = JSON.parse(new TextDecoder().decode(await readBoundedBody(response.body, ERROR_BODY_LIMIT, AbortSignal.timeout(SESSION_TIMEOUT_MS))));
      if (!isRecord(payload)) throw new Error("Invalid desktop free status.");
      const allowance = payload.allowance;
      let validatedAllowance: DesktopFreeAccessStatus["allowance"] = null;
      if (isRecord(allowance) && typeof allowance.limitUsd === "number" && typeof allowance.usedUsd === "number"
        && typeof allowance.reservedUsd === "number" && typeof allowance.remainingUsd === "number" && typeof allowance.resetsAt === "string"
        && [allowance.limitUsd, allowance.usedUsd, allowance.reservedUsd, allowance.remainingUsd].every((value) => Number.isFinite(value) && value >= 0)) {
        validatedAllowance = { limitUsd: allowance.limitUsd, usedUsd: allowance.usedUsd, reservedUsd: allowance.reservedUsd, remainingUsd: allowance.remainingUsd, resetsAt: allowance.resetsAt };
      }
      const state = payload.state;
      if (state !== "ready" && state !== "update_required" && state !== "unavailable" && state !== "exhausted") throw new Error("Invalid desktop free status state.");
      if (state === "ready" && (!validatedAllowance || typeof payload.minimumVersion !== "string")) throw new Error("Incomplete desktop free status.");
      const value: DesktopFreeAccessStatus = {
        ...this.unavailable(), state, code: typeof payload.code === "string" ? payload.code : null,
        minimumVersion: typeof payload.minimumVersion === "string" ? payload.minimumVersion : null,
        allowance: validatedAllowance,
        ...(Array.isArray(payload.catalog) ? { catalog: payload.catalog.filter(isRecommendation) } : {}),
      };
      this.cachedStatus = { expiresAt: Date.now() + 10_000, value };
      return value;
    } catch (error) {
      if (error instanceof RemoteFailure) {
        const payload = error.payload();
        const code = typeof payload.code === "string" ? payload.code : "anonymous_unavailable";
        return { ...this.unavailable(code),
          state: code === "desktop_update_required" ? "update_required" : code === "anonymous_limit_exceeded" ? "exhausted" : "unavailable",
          minimumVersion: typeof payload.minimumVersion === "string" ? payload.minimumVersion : null,
        };
      }
      return this.unavailable();
    }
  }

  /** Gate explicitly selected free Luna before the engine accepts a prompt. */
  async assertTaskAccess(request: Request, path: string): Promise<void> {
    if (request.method !== "POST" || !/\/(?:prompt_async|message|command|summarize)$/.test(path)) return;
    const payload: unknown = await request.clone().json().catch(() => null);
    if (!isRecord(payload)) return;
    const model = payload.model;
    const free = isRecord(model) ? model.providerID === DESKTOP_FREE_PROVIDER_ID
      : typeof model === "string" && model.startsWith(`${DESKTOP_FREE_PROVIDER_ID}/`);
    if (!free) return;
    const status = await this.status(true);
    if (status.state !== "ready") {
      throw new ApiError(status.state === "update_required" ? 426 : status.state === "exhausted" ? 429 : 503,
        status.code ?? "anonymous_unavailable", "Free Luna is not available. Check desktop free access status.", status);
    }
  }

  private async remote(path: string, method: string, body: Uint8Array<ArrayBuffer>, authenticated: boolean, signal = AbortSignal.timeout(SESSION_TIMEOUT_MS), retry = true): Promise<Response> {
    await this.assertDispatchAllowed();
    const desktop = this.config.anonymousInference!.desktop;
    const session = authenticated ? await this.guestSession() : null;
    await this.assertDispatchAllowed();
    signal.throwIfAborted();
    const authorization = session ? `Bearer ${session.token}` : "";
    const proof = await desktop.sign({ method, path, body, authorization });
    signal.throwIfAborted();
    const response = await externalFetch(`${this.origin}${path}`, {
      method, body: method === "GET" ? undefined : body,
      headers: { [DESKTOP_FREE_PROOF_HEADER]: proof, ...(authorization ? { authorization } : {}), ...(method === "POST" ? { "content-type": "application/json" } : {}) },
      signal, redirect: "error", credentials: "omit", cache: "no-store",
    });
    if (response.ok) return response;
    const failure = new RemoteFailure(response.status, await readBoundedBody(response.body, ERROR_BODY_LIMIT, signal), responseHeaders(response.headers));
    if (authenticated && retry && failure.status === 401 && failure.payload().code === "invalid_anonymous_token") {
      if (this.session?.token === session?.token) this.session = null;
      return this.remote(path, method, body, authenticated, signal, false);
    }
    throw failure;
  }

  private async guestSession(): Promise<DesktopFreeSession> {
    if (this.session && this.session.expiresAt - 30_000 > Date.now()) return this.session;
    if (this.sessionPromise) return this.sessionPromise;
    const mint = async (): Promise<DesktopFreeSession> => {
      const identity = await this.config.anonymousInference!.desktop.identity();
      // The public-key claim lives in the proof; its signature binds this exact
      // stable installation id to that key without adding session schema fields.
      const body = new TextEncoder().encode(JSON.stringify({ installationId: identity.installationId }));
      const response = await this.remote(DESKTOP_FREE_SESSION_PATH, "POST", body, false);
      const payload: unknown = JSON.parse(new TextDecoder().decode(await readBoundedBody(response.body, ERROR_BODY_LIMIT, AbortSignal.timeout(SESSION_TIMEOUT_MS))));
      if (!isRecord(payload) || typeof payload.token !== "string" || !payload.token.trim()
        || typeof payload.expiresAt !== "number" || !Number.isFinite(payload.expiresAt) || payload.expiresAt <= Date.now()
        || payload.model !== DESKTOP_FREE_MODEL_ID) throw new Error("Invalid desktop free session response.");
      return { token: payload.token, expiresAt: payload.expiresAt, model: payload.model };
    };
    const pending = mint();
    this.sessionPromise = pending;
    try { this.session = await pending; return this.session; }
    finally { if (this.sessionPromise === pending) this.sessionPromise = null; }
  }

  async handle(request: Request, endpoint: "models" | "chat/completions"): Promise<Response> {
    const supplied = Buffer.from(request.headers.get("authorization")?.match(/^Bearer\s+(.+)$/i)?.[1] ?? "");
    const expected = Buffer.from(this.localAccessToken);
    if (supplied.length !== expected.length || !timingSafeEqual(supplied, expected)) return jsonError(401, "invalid_local_anonymous_token", "The local OpenWork Models credential is invalid.");
    if (request.method !== (endpoint === "models" ? "GET" : "POST")) return jsonError(405, "method_not_allowed", "Unsupported OpenWork Models method.");
    const controller = new AbortController();
    this.activeControllers.add(controller);
    const signal = AbortSignal.any([request.signal, controller.signal]);
    const timer = setTimeout(() => controller.abort(new Error("Desktop free inference request timed out.")), REQUEST_LIFETIME_MS);
    let streaming = false;
    const cleanup = () => { clearTimeout(timer); this.activeControllers.delete(controller); };
    let requestKey = "";
    try {
      await this.assertDispatchAllowed();
      const declaredLength = Number(request.headers.get("content-length") ?? "0");
      if (declaredLength > REQUEST_BODY_LIMIT) return jsonError(413, "anonymous_request_too_large", "The OpenWork Models request is too large.");
      const body = await readBoundedBody(request.body, REQUEST_BODY_LIMIT, AbortSignal.any([signal, AbortSignal.timeout(15_000)]));
      requestKey = createHash("sha256").update(endpoint).update(body).digest("hex");
      const cached = this.failures.get(requestKey);
      if (cached && cached.expiresAt > Date.now()) return cached.failure.response();
      // Check the latest floor before generation, even with a cached bearer.
      // The gateway independently rechecks it on the actual generation request.
      if (endpoint !== "models") {
        const status = await this.status(true);
        if (status.state !== "ready") return Response.json({ error: { ...status, message: "Free Luna is not available.", type: "openwork_anonymous_error" } }, {
          status: status.state === "update_required" ? 426 : status.state === "exhausted" ? 429 : 503,
        });
      }
      const headerTimeout = setTimeout(() => controller.abort(new Error("Desktop free inference response headers timed out.")), 30_000);
      let response: Response;
      try { response = await this.remote(endpoint === "models" ? DESKTOP_FREE_MODELS_PATH : DESKTOP_FREE_CHAT_PATH, request.method, body, true, signal); }
      finally { clearTimeout(headerTimeout); }
      this.cachedStatus = null;
      if (!response.body) return new Response(null, { status: response.status, headers: responseHeaders(response.headers) });
      const reader = response.body.getReader();
      const abort = () => { void reader.cancel(signal.reason).catch(() => undefined); cleanup(); };
      signal.addEventListener("abort", abort, { once: true });
      const finish = () => { signal.removeEventListener("abort", abort); cleanup(); };
      streaming = true;
      return new Response(new ReadableStream<Uint8Array>({
        async pull(output) {
          try {
            signal.throwIfAborted();
            const chunk = await reader.read();
            signal.throwIfAborted();
            if (chunk.done) { finish(); output.close(); } else output.enqueue(chunk.value);
          } catch (error) { finish(); output.error(error); }
        },
        async cancel(reason) { controller.abort(reason); finish(); await reader.cancel(reason).catch(() => undefined); },
      }), { status: response.status, headers: responseHeaders(response.headers) });
    } catch (error) {
      if (request.signal.aborted) throw error;
      if (error instanceof RemoteFailure) {
        const code = error.payload().code;
        if (["anonymous_limit_exceeded", "anonymous_capacity_exceeded", "anonymous_unavailable"].includes(String(code))) {
          error.headers.set("x-openwork-anonymous-no-upstream-retry", "1");
          if (this.failures.size >= 64) this.failures.clear();
          this.failures.set(requestKey, { expiresAt: Date.now() + 30_000, failure: error });
        }
        return error.response();
      }
      if (error instanceof ApiError) return jsonError(error.status, error.code, error.message);
      this.logger.log("warn", "Desktop free inference failed before a response began.");
      return jsonError(503, "anonymous_unavailable", "Free Luna is temporarily unavailable. Try again later or use your own provider.");
    } finally { if (!streaming) cleanup(); }
  }

  private disable(): void {
    this.available = false;
    this.session = null;
    this.cachedStatus = null;
    for (const controller of this.activeControllers) controller.abort(new Error("Desktop free inference disabled."));
    this.activeControllers.clear();
  }

  stop(): void { this.stopped = true; this.disable(); this.failures.clear(); }
}
