/**
 * Generate builtin-skills.ts from SKILL.md files.
 * This script reads skill files and generates a TypeScript file with embedded content,
 * so that bun build --compile can include them in the single-file executable.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = join(__dirname, "..", "src", "builtin-skills");
const outFile = join(__dirname, "..", "src", "generated-builtin-skills.ts");

async function main() {
  const skills: { name: string; content: string }[] = [];

  try {
    const entries = await readdir(srcDir, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      const skillPath = join(srcDir, entry.name, "SKILL.md");
      try {
        const content = await readFile(skillPath, "utf8");
        skills.push({ name: entry.name, content });
      } catch {
        // Skip if SKILL.md doesn't exist
      }
    }
  } catch {
    // Directory doesn't exist, generate empty fallback
    console.log("No builtin-skills directory found, generating empty fallback");
  }

  // Generate TypeScript file
  const tsContent = `// Auto-generated by script/generate-builtin-skills.ts
// DO NOT EDIT - regenerate by running: bun script/generate-builtin-skills.ts

import type { SkillItem } from "./types.js";
import { parseFrontmatter } from "./frontmatter.js";
import { validateSkillName, validateDescription } from "./validators.js";

const extractTriggerFromBody = (body: string): string => {
  const lines = body.split(/\\r?\\n/);
  let inWhenSection = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    if (/^#{1,6}\\s+/.test(trimmed)) {
      const heading = trimmed.replace(/^#{1,6}\\s+/, "").trim();
      inWhenSection = /^when to use$/i.test(heading);
      continue;
    }

    if (!inWhenSection) continue;

    const cleaned = trimmed
      .replace(/^[-*+]\\s+/, "")
      .replace(/^\\d+[.)]\\s+/, "")
      .trim();

    if (cleaned) return cleaned;
  }

  return "";
};

const BUILTIN_SKILLS_CONTENT: Map<string, string> = new Map([
${skills.map((s) => `  [${JSON.stringify(s.name)}, ${JSON.stringify(s.content)}]`).join(",\n")}
]);

export async function listBuiltinSkills(): Promise<SkillItem[]> {
  const items: SkillItem[] = [];

  for (const [name, content] of BUILTIN_SKILLS_CONTENT) {
    const { data, body } = parseFrontmatter(content);
    const skillName = typeof data.name === "string" ? data.name : name;
    const description = typeof data.description === "string" ? data.description : "";
    const trigger =
      typeof data.trigger === "string"
        ? data.trigger
        : typeof data.when === "string"
          ? data.when
          : extractTriggerFromBody(body);

    try {
      validateSkillName(skillName);
      validateDescription(description);
    } catch {
      continue;
    }

    items.push({
      name: skillName,
      description,
      path: \`builtin://\${name}\`,
      scope: "global",
      trigger: trigger.trim() || undefined,
    });
  }

  return items;
}

export function getBuiltinSkillContent(name: string): string | undefined {
  return BUILTIN_SKILLS_CONTENT.get(name);
}
`;

  await writeFile(outFile, tsContent, "utf8");
  console.log(`Generated ${outFile} with ${skills.length} skill(s)`);
}

main().catch((err) => {
  console.error("Failed to generate builtin skills:", err);
  process.exit(1);
});
