import { githubSyncRoutePaths } from "../../../modules/marketplace/github-sync/contracts.js"

const orgBasePath = "/v1"

export const pluginArchRoutePaths = {
  configObjects: `${orgBasePath}/config-objects`,
  configObject: `${orgBasePath}/config-objects/:configObjectId`,
  configObjectArchive: `${orgBasePath}/config-objects/:configObjectId/archive`,
  configObjectDelete: `${orgBasePath}/config-objects/:configObjectId/delete`,
  configObjectRestore: `${orgBasePath}/config-objects/:configObjectId/restore`,
  configObjectPlugins: `${orgBasePath}/config-objects/:configObjectId/plugins`,
  configObjectPlugin: `${orgBasePath}/config-objects/:configObjectId/plugins/:pluginId`,
  configObjectAccess: `${orgBasePath}/config-objects/:configObjectId/access`,
  configObjectAccessGrant: `${orgBasePath}/config-objects/:configObjectId/access/:grantId`,
  configObjectVersions: `${orgBasePath}/config-objects/:configObjectId/versions`,
  configObjectVersion: `${orgBasePath}/config-objects/:configObjectId/versions/:versionId`,
  configObjectLatestVersion: `${orgBasePath}/config-objects/:configObjectId/versions/latest`,
  configObjectCompareVersions: `${orgBasePath}/config-objects/:configObjectId/versions/compare`,
  skills: `${orgBasePath}/skills`,
  agents: `${orgBasePath}/agents`,
  commands: `${orgBasePath}/commands`,
  tools: `${orgBasePath}/tools`,
  mcps: `${orgBasePath}/mcps`,
  plugins: `${orgBasePath}/plugins`,
  plugin: `${orgBasePath}/plugins/:pluginId`,
  pluginArchive: `${orgBasePath}/plugins/:pluginId/archive`,
  pluginRestore: `${orgBasePath}/plugins/:pluginId/restore`,
  pluginConfigObjects: `${orgBasePath}/plugins/:pluginId/config-objects`,
  pluginConfigObject: `${orgBasePath}/plugins/:pluginId/config-objects/:configObjectId`,
  pluginMcpConnections: `${orgBasePath}/plugins/:pluginId/mcp-connections`,
  pluginResolved: `${orgBasePath}/plugins/:pluginId/resolved`,
  pluginReleases: `${orgBasePath}/plugins/:pluginId/releases`,
  pluginAccess: `${orgBasePath}/plugins/:pluginId/access`,
  pluginAccessGrant: `${orgBasePath}/plugins/:pluginId/access/:grantId`,
  meLibrary: `${orgBasePath}/me/library`,
  mePluginAccess: `${orgBasePath}/me/plugin-access`,
  teamPluginAccess: `${orgBasePath}/teams/:teamId/plugin-access`,
  pluginGithubMcpImportPreview: `${orgBasePath}/plugins/import-mcps-from-github-url/preview`,
  pluginGithubMcpImport: `${orgBasePath}/plugins/import-mcps-from-github-url`,
  marketplaces: `${orgBasePath}/marketplaces`,
  marketplace: `${orgBasePath}/marketplaces/:marketplaceId`,
  marketplaceResolved: `${orgBasePath}/marketplaces/:marketplaceId/resolved`,
  marketplaceArchive: `${orgBasePath}/marketplaces/:marketplaceId/archive`,
  marketplaceDelete: `${orgBasePath}/marketplaces/:marketplaceId/delete`,
  marketplaceRestore: `${orgBasePath}/marketplaces/:marketplaceId/restore`,
  marketplacePlugins: `${orgBasePath}/marketplaces/:marketplaceId/plugins`,
  marketplacePlugin: `${orgBasePath}/marketplaces/:marketplaceId/plugins/:pluginId`,
  marketplaceAccess: `${orgBasePath}/marketplaces/:marketplaceId/access`,
  marketplaceAccessGrant: `${orgBasePath}/marketplaces/:marketplaceId/access/:grantId`,
  ...githubSyncRoutePaths,
} as const
