/** @deprecated Moved to modules/marketplace/github-sync/github-app.ts (W0-P03); removed by M-marketplace.githubSync. */
export {
  buildGithubAppInstallUrl,
  clearGithubInstallationTokenCache,
  createGithubAppJwt,
  createGithubInstallStateToken,
  fetchGithubImportFilesWithRevisionGuard,
  getGithubAppSummary,
  getGithubConnectorAppConfig,
  getGithubInstallationAccessToken,
  getGithubInstallationSummary,
  getGithubRepositoryHeadSha,
  getGithubRepositoryTextFile,
  getGithubRepositoryTree,
  type GithubAppSummary,
  type GithubConnectorAppConfig,
  GithubConnectorConfigError,
  GithubConnectorRequestError,
  type GithubImportFileFetchResult,
  type GithubImportFilePlan,
  type GithubInstallationSummary,
  type GithubInstallStatePayload,
  type GithubManifestKind,
  type GithubRepositoryTreeEntry,
  type GithubRepositoryTreeSnapshot,
  listGithubInstallationRepositories,
  normalizeGithubPrivateKey,
  validateGithubInstallationTarget,
  verifyGithubInstallStateToken,
} from "../../../modules/marketplace/github-sync/github-app.js"
