import type { Accessor } from "solid-js";

import type { DashboardViewProps } from "../pages/dashboard";

type DashboardPropsBuilderInput = {
  tab: Accessor<DashboardViewProps["tab"]>;
  setTab: DashboardViewProps["setTab"];
  settingsTab: Accessor<DashboardViewProps["settingsTab"]>;
  setSettingsTab: DashboardViewProps["setSettingsTab"];
  setView: DashboardViewProps["setView"];
  toggleSettings: DashboardViewProps["toggleSettings"];
  startupPreference: Accessor<DashboardViewProps["startupPreference"]>;
  baseUrl: Accessor<DashboardViewProps["baseUrl"]>;
  clientConnected: Accessor<DashboardViewProps["clientConnected"]>;
  busy: Accessor<DashboardViewProps["busy"]>;
  busyHint: Accessor<DashboardViewProps["busyHint"]>;
  newTaskDisabled: Accessor<DashboardViewProps["newTaskDisabled"]>;
  headerStatus: Accessor<DashboardViewProps["headerStatus"]>;
  error: Accessor<DashboardViewProps["error"]>;
  activeWorkspaceType: Accessor<DashboardViewProps["activeWorkspaceType"]>;
  opencodeConnectStatus: Accessor<DashboardViewProps["opencodeConnectStatus"]>;
  engineInfo: Accessor<DashboardViewProps["engineInfo"]>;
  orchestratorStatus: Accessor<DashboardViewProps["orchestratorStatus"]>;
  opencodeRouterInfo: Accessor<DashboardViewProps["opencodeRouterInfo"]>;
  engineDoctorVersion: Accessor<DashboardViewProps["engineDoctorVersion"]>;
  updateOpenworkServerSettings: DashboardViewProps["updateOpenworkServerSettings"];
  resetOpenworkServerSettings: DashboardViewProps["resetOpenworkServerSettings"];
  testOpenworkServerConnection: DashboardViewProps["testOpenworkServerConnection"];
  canReloadWorkspace: Accessor<DashboardViewProps["canReloadWorkspace"]>;
  reloadWorkspaceEngine: DashboardViewProps["reloadWorkspaceEngine"];
  reloadBusy: Accessor<DashboardViewProps["reloadBusy"]>;
  reloadError: Accessor<DashboardViewProps["reloadError"]>;
  workspaceAutoReloadAvailable: Accessor<DashboardViewProps["workspaceAutoReloadAvailable"]>;
  workspaceAutoReloadEnabled: Accessor<DashboardViewProps["workspaceAutoReloadEnabled"]>;
  setWorkspaceAutoReloadEnabled: DashboardViewProps["setWorkspaceAutoReloadEnabled"];
  workspaceAutoReloadResumeEnabled: Accessor<DashboardViewProps["workspaceAutoReloadResumeEnabled"]>;
  setWorkspaceAutoReloadResumeEnabled: DashboardViewProps["setWorkspaceAutoReloadResumeEnabled"];
  selectedWorkspaceDisplay: Accessor<DashboardViewProps["selectedWorkspaceDisplay"]>;
  workspaces: Accessor<DashboardViewProps["workspaces"]>;
  selectedWorkspaceId: Accessor<DashboardViewProps["selectedWorkspaceId"]>;
  connectingWorkspaceId: Accessor<DashboardViewProps["connectingWorkspaceId"]>;
  workspaceConnectionStateById: Accessor<DashboardViewProps["workspaceConnectionStateById"]>;
  switchWorkspace: DashboardViewProps["switchWorkspace"];
  testWorkspaceConnection: DashboardViewProps["testWorkspaceConnection"];
  recoverWorkspace: DashboardViewProps["recoverWorkspace"];
  workspaceSessionGroups: Accessor<DashboardViewProps["workspaceSessionGroups"]>;
  selectedSessionId: Accessor<DashboardViewProps["selectedSessionId"]>;
  openRenameWorkspace: DashboardViewProps["openRenameWorkspace"];
  editWorkspaceConnection: DashboardViewProps["editWorkspaceConnection"];
  forgetWorkspace: DashboardViewProps["forgetWorkspace"];
  selectedWorkspaceRoot: Accessor<DashboardViewProps["selectedWorkspaceRoot"]>;
  isRemoteWorkspace: Accessor<DashboardViewProps["isRemoteWorkspace"]>;
  createSessionAndOpen: DashboardViewProps["createSessionAndOpen"];
  setPrompt: DashboardViewProps["setPrompt"];
  selectSession: DashboardViewProps["selectSession"];
  defaultModelLabel: Accessor<DashboardViewProps["defaultModelLabel"]>;
  defaultModelRef: Accessor<DashboardViewProps["defaultModelRef"]>;
  openDefaultModelPicker: DashboardViewProps["openDefaultModelPicker"];
  showThinking: Accessor<DashboardViewProps["showThinking"]>;
  toggleShowThinking: DashboardViewProps["toggleShowThinking"];
  autoCompactContext: Accessor<DashboardViewProps["autoCompactContext"]>;
  toggleAutoCompactContext: DashboardViewProps["toggleAutoCompactContext"];
  autoCompactContextBusy: Accessor<DashboardViewProps["autoCompactContextBusy"]>;
  hideTitlebar: Accessor<DashboardViewProps["hideTitlebar"]>;
  toggleHideTitlebar: DashboardViewProps["toggleHideTitlebar"];
  modelVariantLabel: Accessor<DashboardViewProps["modelVariantLabel"]>;
  editModelVariant: DashboardViewProps["editModelVariant"];
  updateAutoCheck: Accessor<DashboardViewProps["updateAutoCheck"]>;
  toggleUpdateAutoCheck: DashboardViewProps["toggleUpdateAutoCheck"];
  updateAutoDownload: Accessor<DashboardViewProps["updateAutoDownload"]>;
  toggleUpdateAutoDownload: DashboardViewProps["toggleUpdateAutoDownload"];
  updateStatus: Accessor<DashboardViewProps["updateStatus"]>;
  updateEnv: Accessor<DashboardViewProps["updateEnv"]>;
  appVersion: Accessor<DashboardViewProps["appVersion"]>;
  checkForUpdates: DashboardViewProps["checkForUpdates"];
  downloadUpdate: DashboardViewProps["downloadUpdate"];
  installUpdateAndRestart: DashboardViewProps["installUpdateAndRestart"];
  anyActiveRuns: Accessor<DashboardViewProps["anyActiveRuns"]>;
  engineSource: Accessor<DashboardViewProps["engineSource"]>;
  setEngineSource: DashboardViewProps["setEngineSource"];
  engineCustomBinPath: Accessor<DashboardViewProps["engineCustomBinPath"]>;
  setEngineCustomBinPath: DashboardViewProps["setEngineCustomBinPath"];
  engineRuntime: Accessor<DashboardViewProps["engineRuntime"]>;
  setEngineRuntime: DashboardViewProps["setEngineRuntime"];
  opencodeEnableExa: Accessor<DashboardViewProps["opencodeEnableExa"]>;
  toggleOpencodeEnableExa: DashboardViewProps["toggleOpencodeEnableExa"];
  isWindows: Accessor<DashboardViewProps["isWindows"]>;
  toggleDeveloperMode: DashboardViewProps["toggleDeveloperMode"];
  developerMode: Accessor<DashboardViewProps["developerMode"]>;
  stopHost: DashboardViewProps["stopHost"];
  restartLocalServer: DashboardViewProps["restartLocalServer"];
  openResetModal: DashboardViewProps["openResetModal"];
  resetModalBusy: Accessor<DashboardViewProps["resetModalBusy"]>;
  onResetStartupPreference: DashboardViewProps["onResetStartupPreference"];
  themeMode: Accessor<DashboardViewProps["themeMode"]>;
  setThemeMode: DashboardViewProps["setThemeMode"];
  pendingPermissions: Accessor<DashboardViewProps["pendingPermissions"]>;
  events: Accessor<DashboardViewProps["events"]>;
  workspaceDebugEvents: Accessor<DashboardViewProps["workspaceDebugEvents"]>;
  sandboxCreateProgress: Accessor<DashboardViewProps["sandboxCreateProgress"]>;
  sandboxCreateProgressLast: Accessor<DashboardViewProps["sandboxCreateProgressLast"]>;
  clearWorkspaceDebugEvents: DashboardViewProps["clearWorkspaceDebugEvents"];
  safeStringify: DashboardViewProps["safeStringify"];
  resetAppConfigDefaults: DashboardViewProps["resetAppConfigDefaults"];
  openDebugDeepLink: DashboardViewProps["openDebugDeepLink"];
  mcpServers: Accessor<DashboardViewProps["mcpServers"]>;
  mcpStatus: Accessor<DashboardViewProps["mcpStatus"]>;
  mcpLastUpdatedAt: Accessor<DashboardViewProps["mcpLastUpdatedAt"]>;
  mcpStatuses: Accessor<DashboardViewProps["mcpStatuses"]>;
  mcpConnectingName: Accessor<DashboardViewProps["mcpConnectingName"]>;
  selectedMcp: Accessor<DashboardViewProps["selectedMcp"]>;
  setSelectedMcp: DashboardViewProps["setSelectedMcp"];
  quickConnect: DashboardViewProps["quickConnect"];
  connectMcp: DashboardViewProps["connectMcp"];
  authorizeMcp: DashboardViewProps["authorizeMcp"];
  logoutMcpAuth: DashboardViewProps["logoutMcpAuth"];
  removeMcp: DashboardViewProps["removeMcp"];
  refreshMcpServers: DashboardViewProps["refreshMcpServers"];
  language: Accessor<DashboardViewProps["language"]>;
  setLanguage: DashboardViewProps["setLanguage"];
};

export function createDashboardPropsBuilder(input: DashboardPropsBuilderInput) {
  return () => ({
    tab: input.tab(),
    setTab: input.setTab,
    settingsTab: input.settingsTab(),
    setSettingsTab: input.setSettingsTab,
    setView: input.setView,
    toggleSettings: input.toggleSettings,
    startupPreference: input.startupPreference(),
    baseUrl: input.baseUrl(),
    clientConnected: input.clientConnected(),
    busy: input.busy(),
    busyHint: input.busyHint(),
    newTaskDisabled: input.newTaskDisabled(),
    headerStatus: input.headerStatus(),
    error: input.error(),
    activeWorkspaceType: input.activeWorkspaceType(),
    opencodeConnectStatus: input.opencodeConnectStatus(),
    engineInfo: input.engineInfo(),
    orchestratorStatus: input.orchestratorStatus(),
    opencodeRouterInfo: input.opencodeRouterInfo(),
    engineDoctorVersion: input.engineDoctorVersion(),
    updateOpenworkServerSettings: input.updateOpenworkServerSettings,
    resetOpenworkServerSettings: input.resetOpenworkServerSettings,
    testOpenworkServerConnection: input.testOpenworkServerConnection,
    canReloadWorkspace: input.canReloadWorkspace(),
    reloadWorkspaceEngine: input.reloadWorkspaceEngine,
    reloadBusy: input.reloadBusy(),
    reloadError: input.reloadError(),
    workspaceAutoReloadAvailable: input.workspaceAutoReloadAvailable(),
    workspaceAutoReloadEnabled: input.workspaceAutoReloadEnabled(),
    setWorkspaceAutoReloadEnabled: input.setWorkspaceAutoReloadEnabled,
    workspaceAutoReloadResumeEnabled: input.workspaceAutoReloadResumeEnabled(),
    setWorkspaceAutoReloadResumeEnabled: input.setWorkspaceAutoReloadResumeEnabled,
    selectedWorkspaceDisplay: input.selectedWorkspaceDisplay(),
    workspaces: input.workspaces(),
    selectedWorkspaceId: input.selectedWorkspaceId(),
    connectingWorkspaceId: input.connectingWorkspaceId(),
    workspaceConnectionStateById: input.workspaceConnectionStateById(),
    switchWorkspace: input.switchWorkspace,
    testWorkspaceConnection: input.testWorkspaceConnection,
    recoverWorkspace: input.recoverWorkspace,
    workspaceSessionGroups: input.workspaceSessionGroups(),
    selectedSessionId: input.selectedSessionId(),
    openRenameWorkspace: input.openRenameWorkspace,
    editWorkspaceConnection: input.editWorkspaceConnection,
    forgetWorkspace: input.forgetWorkspace,
    selectedWorkspaceRoot: input.selectedWorkspaceRoot(),
    isRemoteWorkspace: input.isRemoteWorkspace(),
    refreshMcpServers: input.refreshMcpServers,
    mcpServers: input.mcpServers(),
    mcpStatus: input.mcpStatus(),
    mcpLastUpdatedAt: input.mcpLastUpdatedAt(),
    mcpStatuses: input.mcpStatuses(),
    mcpConnectingName: input.mcpConnectingName(),
    selectedMcp: input.selectedMcp(),
    setSelectedMcp: input.setSelectedMcp,
    quickConnect: input.quickConnect,
    connectMcp: input.connectMcp,
    authorizeMcp: input.authorizeMcp,
    logoutMcpAuth: input.logoutMcpAuth,
    removeMcp: input.removeMcp,
    createSessionAndOpen: input.createSessionAndOpen,
    setPrompt: input.setPrompt,
    selectSession: input.selectSession,
    defaultModelLabel: input.defaultModelLabel(),
    defaultModelRef: input.defaultModelRef(),
    openDefaultModelPicker: input.openDefaultModelPicker,
    showThinking: input.showThinking(),
    toggleShowThinking: input.toggleShowThinking,
    autoCompactContext: input.autoCompactContext(),
    toggleAutoCompactContext: input.toggleAutoCompactContext,
    autoCompactContextBusy: input.autoCompactContextBusy(),
    hideTitlebar: input.hideTitlebar(),
    toggleHideTitlebar: input.toggleHideTitlebar,
    opencodeEnableExa: input.opencodeEnableExa(),
    toggleOpencodeEnableExa: input.toggleOpencodeEnableExa,
    modelVariantLabel: input.modelVariantLabel(),
    editModelVariant: input.editModelVariant,
    language: input.language(),
    setLanguage: input.setLanguage,
    updateAutoCheck: input.updateAutoCheck(),
    toggleUpdateAutoCheck: input.toggleUpdateAutoCheck,
    updateAutoDownload: input.updateAutoDownload(),
    toggleUpdateAutoDownload: input.toggleUpdateAutoDownload,
    themeMode: input.themeMode(),
    setThemeMode: input.setThemeMode,
    updateStatus: input.updateStatus(),
    updateEnv: input.updateEnv(),
    appVersion: input.appVersion(),
    checkForUpdates: input.checkForUpdates,
    downloadUpdate: input.downloadUpdate,
    installUpdateAndRestart: input.installUpdateAndRestart,
    anyActiveRuns: input.anyActiveRuns(),
    engineSource: input.engineSource(),
    setEngineSource: input.setEngineSource,
    engineCustomBinPath: input.engineCustomBinPath(),
    setEngineCustomBinPath: input.setEngineCustomBinPath,
    engineRuntime: input.engineRuntime(),
    setEngineRuntime: input.setEngineRuntime,
    isWindows: input.isWindows(),
    toggleDeveloperMode: input.toggleDeveloperMode,
    developerMode: input.developerMode(),
    stopHost: input.stopHost,
    restartLocalServer: input.restartLocalServer,
    openResetModal: input.openResetModal,
    resetModalBusy: input.resetModalBusy(),
    onResetStartupPreference: input.onResetStartupPreference,
    pendingPermissions: input.pendingPermissions(),
    events: input.events(),
    workspaceDebugEvents: input.workspaceDebugEvents(),
    sandboxCreateProgress: input.sandboxCreateProgress(),
    sandboxCreateProgressLast: input.sandboxCreateProgressLast(),
    clearWorkspaceDebugEvents: input.clearWorkspaceDebugEvents,
    safeStringify: input.safeStringify,
    resetAppConfigDefaults: input.resetAppConfigDefaults,
    openDebugDeepLink: input.openDebugDeepLink,
  });
}
