import type { Accessor } from "solid-js";

import type { SessionViewProps } from "../pages/session";

type SessionPropsBuilderInput = {
  booting: Accessor<SessionViewProps["booting"]>;
  selectedSessionId: Accessor<SessionViewProps["selectedSessionId"]>;
  setView: SessionViewProps["setView"];
  setTab: SessionViewProps["setTab"];
  setSettingsTab: SessionViewProps["setSettingsTab"];
  toggleSettings: SessionViewProps["toggleSettings"];
  selectedWorkspaceDisplay: Accessor<SessionViewProps["selectedWorkspaceDisplay"]>;
  selectedWorkspaceRoot: Accessor<SessionViewProps["selectedWorkspaceRoot"]>;
  activeWorkspaceConfig: Accessor<SessionViewProps["activeWorkspaceConfig"]>;
  workspaces: Accessor<SessionViewProps["workspaces"]>;
  selectedWorkspaceId: Accessor<SessionViewProps["selectedWorkspaceId"]>;
  connectingWorkspaceId: Accessor<SessionViewProps["connectingWorkspaceId"]>;
  workspaceConnectionStateById: Accessor<SessionViewProps["workspaceConnectionStateById"]>;
  switchWorkspace: SessionViewProps["switchWorkspace"];
  testWorkspaceConnection: SessionViewProps["testWorkspaceConnection"];
  recoverWorkspace: SessionViewProps["recoverWorkspace"];
  editWorkspaceConnection: SessionViewProps["editWorkspaceConnection"];
  forgetWorkspace: SessionViewProps["forgetWorkspace"];
  clientConnected: Accessor<SessionViewProps["clientConnected"]>;
  engineInfo: Accessor<SessionViewProps["engineInfo"]>;
  engineDoctorVersion: Accessor<SessionViewProps["engineDoctorVersion"]>;
  orchestratorStatus: Accessor<SessionViewProps["orchestratorStatus"]>;
  opencodeRouterInfo: Accessor<SessionViewProps["opencodeRouterInfo"]>;
  appVersion: Accessor<SessionViewProps["appVersion"]>;
  headerStatus: Accessor<SessionViewProps["headerStatus"]>;
  busyHint: Accessor<SessionViewProps["busyHint"]>;
  updateStatus: Accessor<SessionViewProps["updateStatus"]>;
  anyActiveRuns: Accessor<SessionViewProps["anyActiveRuns"]>;
  installUpdateAndRestart: SessionViewProps["installUpdateAndRestart"];
  createSessionAndOpen: SessionViewProps["createSessionAndOpen"];
  sendPromptAsync: SessionViewProps["sendPromptAsync"];
  abortSession: SessionViewProps["abortSession"];
  sessionRevertMessageId: Accessor<SessionViewProps["sessionRevertMessageId"]>;
  undoLastUserMessage: SessionViewProps["undoLastUserMessage"];
  redoLastUserMessage: SessionViewProps["redoLastUserMessage"];
  compactSession: SessionViewProps["compactSession"];
  lastPromptSent: Accessor<SessionViewProps["lastPromptSent"]>;
  retryLastPrompt: SessionViewProps["retryLastPrompt"];
  newTaskDisabled: Accessor<SessionViewProps["newTaskDisabled"]>;
  workspaceSessionGroups: Accessor<SessionViewProps["workspaceSessionGroups"]>;
  openRenameWorkspace: SessionViewProps["openRenameWorkspace"];
  selectSession: SessionViewProps["selectSession"];
  messages: Accessor<SessionViewProps["messages"]>;
  getSessionById: SessionViewProps["getSessionById"];
  getMessagesBySessionId: SessionViewProps["getMessagesBySessionId"];
  ensureSessionLoaded: SessionViewProps["ensureSessionLoaded"];
  sessionLoadingById: SessionViewProps["sessionLoadingById"];
  todos: Accessor<SessionViewProps["todos"]>;
  developerMode: Accessor<SessionViewProps["developerMode"]>;
  showThinking: Accessor<SessionViewProps["showThinking"]>;
  sessionCompactionState: Accessor<SessionViewProps["sessionCompactionState"]>;
  expandedStepIds: Accessor<SessionViewProps["expandedStepIds"]>;
  setExpandedStepIds: SessionViewProps["setExpandedStepIds"];
  workingFiles: Accessor<SessionViewProps["workingFiles"]>;
  mcpStatuses: Accessor<SessionViewProps["mcpStatuses"]>;
  busy: Accessor<SessionViewProps["busy"]>;
  prompt: Accessor<SessionViewProps["prompt"]>;
  setPrompt: SessionViewProps["setPrompt"];
  selectedSessionModelLabel: Accessor<SessionViewProps["selectedSessionModelLabel"]>;
  openSessionModelPicker: SessionViewProps["openSessionModelPicker"];
  modelVariantLabel: Accessor<SessionViewProps["modelVariantLabel"]>;
  modelVariant: Accessor<SessionViewProps["modelVariant"]>;
  modelBehaviorOptions: Accessor<SessionViewProps["modelBehaviorOptions"]>;
  setModelVariant: SessionViewProps["setModelVariant"];
  activePermission: Accessor<SessionViewProps["activePermission"]>;
  showTryNotionPrompt: Accessor<SessionViewProps["showTryNotionPrompt"]>;
  onTryNotionPrompt: SessionViewProps["onTryNotionPrompt"];
  permissionReplyBusy: Accessor<SessionViewProps["permissionReplyBusy"]>;
  respondPermission: SessionViewProps["respondPermission"];
  respondPermissionAndRemember: SessionViewProps["respondPermissionAndRemember"];
  activeQuestion: Accessor<SessionViewProps["activeQuestion"]>;
  questionReplyBusy: Accessor<SessionViewProps["questionReplyBusy"]>;
  respondQuestion: SessionViewProps["respondQuestion"];
  safeStringify: SessionViewProps["safeStringify"];
  error: Accessor<SessionViewProps["error"]>;
  sessionStatus: Accessor<SessionViewProps["sessionStatus"]>;
  renameSession: SessionViewProps["renameSession"];
  listAgents: SessionViewProps["listAgents"];
  searchFiles: SessionViewProps["searchFiles"];
  listCommands: SessionViewProps["listCommands"];
  selectedSessionAgent: Accessor<SessionViewProps["selectedSessionAgent"]>;
  setSessionAgent: SessionViewProps["setSessionAgent"];
  sessionStatusById: Accessor<SessionViewProps["sessionStatusById"]>;
  hasEarlierMessages: Accessor<SessionViewProps["hasEarlierMessages"]>;
  loadingEarlierMessages: Accessor<SessionViewProps["loadingEarlierMessages"]>;
  loadEarlierMessages: SessionViewProps["loadEarlierMessages"];
  deleteSession: SessionViewProps["deleteSession"];
};

export function createSessionPropsBuilder(input: SessionPropsBuilderInput) {
  return () => ({
    booting: input.booting(),
    selectedSessionId: input.selectedSessionId(),
    setView: input.setView,
    setTab: input.setTab,
    setSettingsTab: input.setSettingsTab,
    toggleSettings: input.toggleSettings,
    selectedWorkspaceDisplay: input.selectedWorkspaceDisplay(),
    selectedWorkspaceRoot: input.selectedWorkspaceRoot(),
    activeWorkspaceConfig: input.activeWorkspaceConfig(),
    workspaces: input.workspaces(),
    selectedWorkspaceId: input.selectedWorkspaceId(),
    connectingWorkspaceId: input.connectingWorkspaceId(),
    workspaceConnectionStateById: input.workspaceConnectionStateById(),
    switchWorkspace: input.switchWorkspace,
    testWorkspaceConnection: input.testWorkspaceConnection,
    recoverWorkspace: input.recoverWorkspace,
    editWorkspaceConnection: input.editWorkspaceConnection,
    forgetWorkspace: input.forgetWorkspace,
    clientConnected: input.clientConnected(),
    engineInfo: input.engineInfo(),
    engineDoctorVersion: input.engineDoctorVersion(),
    orchestratorStatus: input.orchestratorStatus(),
    opencodeRouterInfo: input.opencodeRouterInfo(),
    appVersion: input.appVersion(),
    headerStatus: input.headerStatus(),
    busyHint: input.busyHint(),
    updateStatus: input.updateStatus(),
    anyActiveRuns: input.anyActiveRuns(),
    installUpdateAndRestart: input.installUpdateAndRestart,
    createSessionAndOpen: input.createSessionAndOpen,
    sendPromptAsync: input.sendPromptAsync,
    abortSession: input.abortSession,
    sessionRevertMessageId: input.sessionRevertMessageId(),
    undoLastUserMessage: input.undoLastUserMessage,
    redoLastUserMessage: input.redoLastUserMessage,
    compactSession: input.compactSession,
    lastPromptSent: input.lastPromptSent(),
    retryLastPrompt: input.retryLastPrompt,
    newTaskDisabled: input.newTaskDisabled(),
    workspaceSessionGroups: input.workspaceSessionGroups(),
    openRenameWorkspace: input.openRenameWorkspace,
    selectSession: input.selectSession,
    messages: input.messages(),
    getSessionById: input.getSessionById,
    getMessagesBySessionId: input.getMessagesBySessionId,
    ensureSessionLoaded: input.ensureSessionLoaded,
    sessionLoadingById: input.sessionLoadingById,
    todos: input.todos(),
    developerMode: input.developerMode(),
    showThinking: input.showThinking(),
    sessionCompactionState: input.sessionCompactionState(),
    expandedStepIds: input.expandedStepIds(),
    setExpandedStepIds: input.setExpandedStepIds,
    workingFiles: input.workingFiles(),
    mcpStatuses: input.mcpStatuses(),
    busy: input.busy(),
    prompt: input.prompt(),
    setPrompt: input.setPrompt,
    selectedSessionModelLabel: input.selectedSessionModelLabel(),
    openSessionModelPicker: input.openSessionModelPicker,
    modelVariantLabel: input.modelVariantLabel(),
    modelVariant: input.modelVariant(),
    modelBehaviorOptions: input.modelBehaviorOptions(),
    setModelVariant: input.setModelVariant,
    activePermission: input.activePermission(),
    showTryNotionPrompt: input.showTryNotionPrompt(),
    onTryNotionPrompt: input.onTryNotionPrompt,
    permissionReplyBusy: input.permissionReplyBusy(),
    respondPermission: input.respondPermission,
    respondPermissionAndRemember: input.respondPermissionAndRemember,
    activeQuestion: input.activeQuestion(),
    questionReplyBusy: input.questionReplyBusy(),
    respondQuestion: input.respondQuestion,
    safeStringify: input.safeStringify,
    error: input.error(),
    sessionStatus: input.sessionStatus(),
    renameSession: input.renameSession,
    listAgents: input.listAgents,
    searchFiles: input.searchFiles,
    listCommands: input.listCommands,
    selectedSessionAgent: input.selectedSessionAgent(),
    setSessionAgent: input.setSessionAgent,
    sessionStatusById: input.sessionStatusById(),
    hasEarlierMessages: input.hasEarlierMessages(),
    loadingEarlierMessages: input.loadingEarlierMessages(),
    loadEarlierMessages: input.loadEarlierMessages,
    deleteSession: input.deleteSession,
  });
}
