import assert from "node:assert/strict";
import { createServer } from "node:http";
import { test } from "node:test";
import { createCoworkerThreads } from "../../../apps/coworker/src/lib/threads.ts";
import { resolveWorkerModel } from "../../../apps/coworker/electron/workers.mjs";
import { createNativeV2Client, nativeCatalogProviders } from "./v2.ts";

test("renderer uses native scoped controls, preserves option values, and requires connection evidence", async (t) => {
  const mount = "/workspace/ws_fixture/opencode2/api";
  const sid = "ses_fixture";
  const requests = [];
  const permission = { id: "per_fixture", sessionID: sid, action: "shell", resources: ["pwd"], source: { type: "tool", messageID: "msg_reply", id: "call_shell" }, save: ["pwd"] };
  const form = { id: "frm_fixture", sessionID: sid, title: "Question", metadata: { kind: "question", tool: { messageID: "msg_reply", id: "call_question" } }, fields: [{ type: "string", key: "choice", title: "Choose", description: "Which option?", custom: false, options: [{ label: "Visible label", value: "native-value" }] }] };
  let currentPermission = permission;
  let currentForm = form;
  let connections = [{ type: "env", name: "FIXTURE_MODEL_KEY" }];
  const model = { id: "fixture", providerID: "connected", modelID: "fixture", name: "Fixture", capabilities: { tools: true, input: ["text"], output: ["text", "reasoning"] }, variants: [{ id: "low" }], time: { released: 1 }, cost: [{ input: 0.1, output: 0.2 }], status: "active", enabled: true, limit: { context: 1000, output: 100 } };
  const server = createServer(async (req, res) => {
    const chunks = []; for await (const chunk of req) chunks.push(Buffer.from(chunk));
    const text = Buffer.concat(chunks).toString();
    const body = text ? JSON.parse(text) : undefined;
    const path = new URL(req.url, "http://fixture.invalid").pathname;
    requests.push({ method: req.method, path, body });
    const send = (value, status = 200) => { res.writeHead(status, { "content-type": "application/json" }); res.end(status === 204 ? undefined : JSON.stringify(value)); };
    if (req.method === "POST") return send(undefined, 204);
    if (path === `${mount}/session/${sid}/permission`) return send({ data: [currentPermission] });
    if (path === `${mount}/session/${sid}/permission/${permission.id}`) return send({ data: currentPermission });
    if (path === `${mount}/session/${sid}/form`) return send({ data: [currentForm] });
    if (path === `${mount}/session/${sid}/form/${form.id}`) return send({ data: currentForm });
    if (path === `${mount}/provider`) return send({ data: [{ id: "connected", name: "Connected", integrationID: "fixture-env", activation: "auto", package: "native", settings: { apiKey: "fixture-not-a-secret", baseURL: "http://fixture:fixture@127.0.0.1:1234/v1?key=fixture" } }, { id: "unconnected", name: "Not connected", activation: "auto", package: "native" }] });
    if (path === `${mount}/integration`) return send({ data: [{ id: "fixture-env", connections }, { id: "unconnected", connections: [] }] });
    if (path === `${mount}/model`) return send({ data: [model, { ...model, providerID: "unconnected" }] });
    if (path === `${mount}/model/default`) return send({ data: model });
    return send({}, 404);
  });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  t.after(() => new Promise((resolve) => { server.close(resolve); server.closeAllConnections(); }));
  const address = server.address(); assert.ok(address && typeof address !== "string");
  const threads = createCoworkerThreads({ serverUrl: `http://127.0.0.1:${address.port}`, workspaceId: "ws_fixture", token: "fixture" });
  const pending = await threads.listThreadInteractions(sid);
  assert.deepEqual(pending.permissions[0].tool, { messageID: "msg_reply", callID: "call_shell" });
  assert.deepEqual(pending.questions[0].tool, { messageID: "msg_reply", callID: "call_question" });
  await threads.replyQuestion(pending.questions[0], [["Visible label"]]);
  assert.deepEqual(requests.at(-1).body, { answer: { choice: "native-value" } });
  assert.equal(requests.at(-1).path, `${mount}/session/${sid}/form/${form.id}/reply`);
  await threads.replyPermission(pending.permissions[0], "once");
  assert.deepEqual(requests.at(-1).body, { reply: "once" });
  currentPermission = { ...permission, resources: ["different command"] };
  let writes = requests.filter((item) => item.method === "POST").length;
  await assert.rejects(threads.replyPermission(pending.permissions[0], "always"), { code: "stale_request" });
  assert.equal(requests.filter((item) => item.method === "POST").length, writes);
  currentForm = { ...form, sessionID: "ses_other" };
  await assert.rejects(threads.rejectQuestion(pending.questions[0]), { code: "stale_request" });
  assert.equal(requests.filter((item) => item.method === "POST").length, writes);
  await assert.rejects(threads.listThreadInteractions(sid), { code: "invalid_response" });
  const catalog = await threads.listModelCatalog();
  assert.deepEqual(catalog.connectedProviderIds, ["connected"]);
  assert.equal(catalog.models.length, 1);
  assert.equal(catalog.models[0].reasoning, true);
  assert.deepEqual(catalog.models[0].variants, ["low"]);
  const native = createNativeV2Client({ baseUrl: `http://127.0.0.1:${address.port}`, workspaceId: "ws_fixture", token: "fixture" });
  const raw = await native.readCatalog();
  const providers = nativeCatalogProviders(raw);
  assert.deepEqual(providers.map((provider) => provider.id), ["connected"]);
  assert.equal(JSON.stringify(providers).includes("apiKey"), false);
  assert.deepEqual(providers[0].options, { baseURL: "http://127.0.0.1:1234" });
  assert.deepEqual(providers[0].models.fixture.cost, { input: 0.1, output: 0.2 });
  assert.equal(nativeCatalogProviders({ ...raw, models: raw.models.map((model) => ({ ...model, cost: [] })) })[0].models.fixture.cost, undefined);
  assert.deepEqual(resolveWorkerModel({ deliveryModel: "connected/fixture", deliveryModelVariant: "low" }, "delivery", providers), { providerId: "connected", modelId: "fixture", variant: "low" });
  connections = [{ type: "credential", id: "cred_fixture", label: "Fixture" }];
  assert.deepEqual((await native.readCatalog()).connectedProviderIds, ["connected"]);
  connections = [];
  assert.deepEqual(nativeCatalogProviders(await native.readCatalog()), []);
  connections = [{ type: "env" }];
  await assert.rejects(native.readCatalog(), { code: "invalid_response" });
  assert.ok(requests.filter((item) => item.path.includes("/session/") || item.path.endsWith("/provider") || item.path.endsWith("/model")).every((item) => item.path.startsWith(mount)));
});
