/**
 * Coworker personalities: a voice for the working state.
 *
 * A personality changes only what the interface says while a coworker is
 * busy — the small line under the thread, the rail label, the Now card. It
 * never changes how the coworker works or writes, and it never replaces a
 * truthful status: "Needs you", "Retrying", "Failed" always win. Sayings are
 * pre-written, work-oriented, and rotate deterministically so every surface
 * that shows the same coworker agrees on the same phrase at the same moment.
 */

export const PERSONALITIES = [
  "none",
  "neutral",
  "warm",
  "calm",
  "eager",
  "playful",
  "dry",
  "blunt",
  "curious",
  "thoughtful",
  "meticulous",
  "detective",
] as const;

export type Personality = (typeof PERSONALITIES)[number];

export const DEFAULT_PERSONALITY: Personality = "neutral";

export const PERSONALITY_OPTIONS: Array<{ id: Personality; label: string; description: string }> = [
  { id: "none", label: "None", description: "Plain status only. Working means working." },
  { id: "neutral", label: "Neutral", description: "Calm, professional progress notes." },
  { id: "warm", label: "Warm", description: "Encouraging, friendly, a little upbeat." },
  { id: "calm", label: "Calm", description: "Unhurried and steady. One step at a time." },
  { id: "eager", label: "Eager", description: "Enthusiastic and quick to dive in." },
  { id: "playful", label: "Playful", description: "Light on its feet; fun without being silly." },
  { id: "dry", label: "Dry", description: "Deadpan understatement. Rarely impressed." },
  { id: "blunt", label: "Blunt", description: "Direct. No fluff, no ceremony." },
  { id: "curious", label: "Curious", description: "An explorer following leads and hunches." },
  { id: "thoughtful", label: "Thoughtful", description: "Reflective; weighs the why before the what." },
  { id: "meticulous", label: "Meticulous", description: "Detail-first. Reads everything twice." },
  { id: "detective", label: "Detective", description: "Follows the trail to the end." },
];

/**
 * Working sayings by personality. Present-participle phrases, no trailing
 * punctuation (the interface adds the ellipsis), nothing that promises a
 * result or describes a specific tool the coworker may not be using.
 */
export const WORKING_SAYINGS: Record<Exclude<Personality, "none">, readonly string[]> = {
  neutral: [
    "Working through it",
    "Reviewing the details",
    "Checking what came back",
    "Lining up the next step",
    "Reading carefully",
    "Making progress",
    "Comparing options",
    "Confirming the facts",
    "Putting the pieces together",
    "Tidying the result",
    "Double-checking",
    "Working on the next part",
    "Getting the details right",
    "Looking at this from another angle",
    "Keeping notes as I go",
    "Verifying before moving on",
    "Sorting what matters from what doesn't",
    "Following the plan",
    "Adjusting the plan",
    "Reviewing the earlier notes",
    "Drafting",
    "Refining the draft",
    "Checking the edge cases",
    "Preparing the summary",
    "Finishing the last step",
    "Almost there",
    "Working steadily",
    "Reading the context",
    "Weighing the trade-offs",
    "Confirming what changed",
    "Cross-checking the numbers",
    "Organizing the findings",
  ],
  warm: [
    "Rolling up my sleeves",
    "Happy to take this one",
    "Getting into it",
    "Making good progress",
    "This is coming together",
    "Nearly there, promise",
    "Giving it a careful look",
    "Taking my time to get it right",
    "Working on something good",
    "Tidying up so it's easy to read",
    "Checking my work",
    "Good news taking shape",
    "One more pass to be sure",
    "Bringing it all together",
    "Reading through your notes",
    "Making sure nothing is missed",
    "Doing the careful part now",
    "Polishing the rough spots",
    "Keeping it simple",
    "Picking up where we left off",
    "Working on it with care",
    "Getting the wording right",
    "Making it clear and useful",
    "Putting the finishing touches on",
    "Almost ready to share",
    "Checking it reads well",
    "Sorting the details",
    "Looking after the small things",
    "Wrapping this up nicely",
    "Taking one more look",
    "Doing my best work here",
    "Glad to be on this",
  ],
  dry: [
    "Doing the boring part properly",
    "Pretending this is easy",
    "Reading the thing nobody read",
    "Consulting the notes, again",
    "Making the obvious explicit",
    "Checking the detail that always bites",
    "Working, allegedly",
    "Confirming what everyone assumed",
    "Finding the catch",
    "Resisting a shortcut",
    "Applying mild skepticism",
    "Doing it the long way, on purpose",
    "Verifying the thing that was 'definitely fine'",
    "Counting to make sure",
    "Un-complicating it",
    "Looking for the footgun",
    "Quietly fixing the typo too",
    "Reading the fine print",
    "Being thorough about it",
    "Removing an adjective",
    "Checking whether it actually works",
    "Making peace with the edge case",
    "Filing this under 'details'",
    "Not rushing this",
    "Making it boring, which is the goal",
    "Trimming the clever part",
    "Reconsidering the plan, briefly",
    "Doing the second check nobody asked for",
    "Keeping expectations modest",
    "Working with the usual enthusiasm",
    "Making sure it's dull enough to trust",
    "Finishing, in a manner of speaking",
  ],
  curious: [
    "Following a hunch",
    "Turning over another stone",
    "Checking the map",
    "Wondering what's behind this",
    "Pulling on a loose thread",
    "Seeing where this leads",
    "Comparing two versions of the story",
    "Asking why, then why again",
    "Poking at the assumption",
    "Tracing it back to the source",
    "Looking around the corner",
    "Testing a small theory",
    "Collecting clues",
    "Noticing a pattern",
    "Reading the part everyone skips",
    "Trying the other door",
    "Following the breadcrumbs",
    "Mapping what I found so far",
    "Chasing down a detail",
    "Peeking under the hood",
    "Connecting two things that shouldn't connect",
    "Checking whether the exception is the rule",
    "Sketching the shape of it",
    "Learning something on the way",
    "Digging one layer deeper",
    "Zooming out for a second",
    "Zooming back in",
    "Finding the interesting part",
    "Retracing my steps",
    "Testing the obvious answer first",
    "Making a note of the surprise",
    "Circling back to the question",
  ],
  calm: [
    "Taking this one step at a time",
    "No rush, doing it right",
    "Keeping a steady pace",
    "Letting the details settle",
    "Moving carefully through this",
    "Staying with it",
    "Keeping things simple",
    "One thing at a time",
    "Quietly getting on with it",
    "Taking the measured route",
    "Checking calmly before moving on",
    "Working without hurry",
    "Settling into the task",
    "Keeping the pace even",
    "Giving this the time it needs",
    "Steady hands on this",
    "Working through it patiently",
    "Not skipping steps",
    "Pausing to make sure",
    "Keeping a level head",
    "Making unhurried progress",
    "Easing through the tricky part",
    "Staying calm about the edge case",
    "Taking stock before continuing",
    "Working in a straight line",
    "Keeping the noise down",
    "Letting the work speak",
    "Finishing without fuss",
    "Rounding this off gently",
    "Breathing room, then the next step",
    "Holding a steady course",
    "Doing the next right thing",
  ],
  eager: [
    "On it already",
    "Diving in",
    "Already halfway there",
    "Picking up speed",
    "Jumping on the next part",
    "Excited about this one",
    "Knocking out the first step",
    "Charging ahead, carefully",
    "Getting a head start",
    "Grabbing the quick wins first",
    "Building momentum",
    "Pushing this forward",
    "Making quick progress",
    "Chasing the next milestone",
    "Getting stuck in",
    "Turning ideas into results",
    "Firing on all cylinders",
    "Keen to get this right",
    "Powering through the details",
    "Sprinting, then checking",
    "Running with it",
    "Bringing energy to the dull part",
    "Loading up the next task",
    "Ready for more",
    "Closing in fast",
    "Nearly done, then the next thing",
    "Making it happen",
    "Going the extra step",
    "Finishing strong",
    "Can't wait to show you this",
    "Racing through the setup",
    "Shipping it",
  ],
  playful: [
    "Poking the problem to see what it does",
    "Nudging the pieces into place",
    "Plotting something useful",
    "Having a quiet word with the details",
    "Making the boring part slightly fun",
    "Sneaking up on the answer",
    "Herding the details",
    "Giving the problem a gentle shake",
    "Untangling the knot",
    "Turning the puzzle over",
    "Trying the clever-but-careful way",
    "Chasing the fun part first",
    "Whistling through the checklist",
    "Making friends with the edge case",
    "Teasing out the answer",
    "Playing with two approaches",
    "Rearranging the furniture",
    "Making the pieces click",
    "Adding a dash of polish",
    "Juggling a few details",
    "Poking around for surprises",
    "Lining up the dominoes",
    "Tuning it until it hums",
    "Keeping it light and correct",
    "Finding the shortcut, then checking it",
    "Making this look easy",
    "Wrapping it with a bow",
    "Sneaking in a small improvement",
    "Working, with a small flourish",
    "Tidying up the fun bits",
    "Doing the dull part with a grin",
    "Making the result a little delightful",
  ],
  blunt: [
    "Getting to the point",
    "Cutting the fluff",
    "Doing the actual work",
    "Skipping the ceremony",
    "Fixing it, not describing it",
    "Saying what's true",
    "Checking the facts, not the vibes",
    "Removing what doesn't matter",
    "Calling it what it is",
    "Working, no commentary",
    "Doing it properly, once",
    "Reading the whole thing",
    "Making it shorter",
    "Getting rid of the hedge",
    "Handling the hard part first",
    "Testing it instead of guessing",
    "Keeping it plain",
    "Doing what was asked",
    "Not dressing it up",
    "Sorting fact from opinion",
    "Cutting to the result",
    "Checking it works",
    "Writing it straight",
    "Dropping the extra step",
    "Making one clear recommendation",
    "Confirming, not assuming",
    "Saying no to scope creep",
    "Trimming it to what matters",
    "Doing the boring, correct thing",
    "Making the call",
    "Finishing the sentence",
    "Wrapping up, no speech",
  ],
  thoughtful: [
    "Thinking this through",
    "Considering the alternatives",
    "Weighing what matters here",
    "Sitting with the question",
    "Looking at the second-order effects",
    "Asking what you'd actually want",
    "Reflecting on the earlier notes",
    "Choosing the simpler explanation",
    "Considering who this affects",
    "Working out the why",
    "Taking the long view",
    "Balancing speed and care",
    "Reconsidering the first idea",
    "Naming the assumption",
    "Thinking about the failure modes",
    "Looking for the underlying cause",
    "Testing the idea against the facts",
    "Choosing my words carefully",
    "Holding two ideas at once",
    "Thinking about what to leave out",
    "Considering the reader",
    "Working from first principles",
    "Checking the reasoning, not just the result",
    "Letting the idea settle",
    "Weighing the cost of being wrong",
    "Finding the crux",
    "Thinking a step ahead",
    "Questioning the default",
    "Drawing the line carefully",
    "Deciding what matters most",
    "Making sense of it",
    "Writing down the reasoning",
  ],
  meticulous: [
    "Checking every line",
    "Reading it twice",
    "Aligning the details",
    "Verifying each step",
    "Leaving nothing to chance",
    "Tidying the loose ends",
    "Making sure the numbers agree",
    "Checking the spelling too",
    "Proofreading as I go",
    "Confirming every assumption",
    "Counting it again",
    "Looking for anything out of place",
    "Getting the small things right",
    "Auditing my own work",
    "Straightening the edges",
    "Matching the source exactly",
    "Following the checklist",
    "Ticking off each item",
    "Testing the edge cases",
    "Making it consistent throughout",
    "Reviewing it line by line",
    "Cross-checking against the notes",
    "Fixing the tiny thing nobody would notice",
    "Making sure it's exactly right",
    "Sorting everything into place",
    "Being thorough, on purpose",
    "Reconciling the last discrepancy",
    "Going over it once more",
    "Being precise about it",
    "Labeling everything clearly",
    "Checking the formatting",
    "Finishing to the last detail",
  ],
  detective: [
    "Following the paper trail",
    "Interviewing the logs",
    "Connecting the dots",
    "Checking the alibi",
    "Looking for what's missing",
    "Dusting for fingerprints",
    "Reconstructing the timeline",
    "Reviewing the evidence",
    "Ruling out the obvious",
    "Questioning the assumption",
    "Examining the scene",
    "Taking notes in shorthand",
    "Comparing the two accounts",
    "Finding the inconsistency",
    "Pulling the file",
    "Tracing the source",
    "Working the case",
    "Following up on a lead",
    "Checking the details twice",
    "Narrowing down the suspects",
    "Reading the small print",
    "Revisiting the first clue",
    "Testing the theory",
    "Corroborating the story",
    "Putting the facts in order",
    "Looking for a motive",
    "Cross-examining the data",
    "Keeping an open mind",
    "Verifying the sequence of events",
    "Closing in on the answer",
    "Writing up the findings",
    "Filing the report",
  ],
};

export function isPersonality(value: unknown): value is Personality {
  return typeof value === "string" && (PERSONALITIES as readonly string[]).includes(value);
}

export function normalizePersonality(value: unknown): Personality {
  return isPersonality(value) ? value : DEFAULT_PERSONALITY;
}

function hashSeed(seed: string): number {
  let hash = 2166136261;
  for (const character of seed) {
    hash ^= character.charCodeAt(0);
    hash = Math.imul(hash, 16777619) >>> 0;
  }
  return hash || 1;
}

/** Small deterministic PRNG so every surface showing a coworker rotates through the same order. */
function seededShuffle<T>(items: readonly T[], seed: string): T[] {
  let state = hashSeed(seed);
  const next = () => {
    state ^= state << 13;
    state >>>= 0;
    state ^= state >>> 17;
    state ^= state << 5;
    state >>>= 0;
    return state / 4294967296;
  };
  const shuffled = [...items];
  for (let index = shuffled.length - 1; index > 0; index -= 1) {
    const swap = Math.floor(next() * (index + 1));
    const held = shuffled[index] as T;
    shuffled[index] = shuffled[swap] as T;
    shuffled[swap] = held;
  }
  return shuffled;
}

/**
 * The saying to show at a given tick. `seed` should identify the coworker and
 * the piece of work (for example `${slug}:${threadId}`) so two coworkers with
 * the same personality do not speak in unison. Returns "" for `none`.
 */
export function workingSaying(personality: Personality, seed: string, tick: number): string {
  if (personality === "none") return "";
  const order = seededShuffle(WORKING_SAYINGS[personality], seed);
  return order[Math.max(0, Math.floor(tick)) % order.length] ?? "";
}

/** A few sayings to preview a personality before choosing it. */
export function previewSayings(personality: Personality, seed: string, count = 3): string[] {
  if (personality === "none") return [];
  return seededShuffle(WORKING_SAYINGS[personality], seed).slice(0, count);
}
