#!/usr/bin/env node
// Keeps everything derived from the feature registry in step with it.
//
//   pnpm features:sync    regenerate the Helm chart's feature block, values
//                         schema and README table from
//                         packages/features/src/registry.ts
//   pnpm features:check   fail if those files are stale, if the chart renders
//                         different DEN_FEATURE_* names than den-api reads, or
//                         if code bypasses the registry (see the rules below)
//
// Read .opencode/skills/add-a-feature/SKILL.md before adding a feature.

import { execFileSync } from "node:child_process"
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"
import {
  FEATURES,
  FEATURE_KEYS,
  featureAvailability,
  featureIsAdjustable,
  featureLockEnvName,
} from "../packages/features/src/index.ts"

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const chartDir = path.join(root, "packaging/helm/openwork-ee")
const valuesPath = path.join(chartDir, "values.yaml")
const schemaPath = path.join(chartDir, "values.schema.json")
const readmePath = path.join(chartDir, "README.md")
const check = process.argv.includes("--check")

const BEGIN = "# BEGIN GENERATED features (pnpm features:sync; source: packages/features/src/registry.ts)"
const END = "# END GENERATED features"
const README_BEGIN = "<!-- BEGIN GENERATED features (pnpm features:sync) -->"
const README_END = "<!-- END GENERATED features -->"

/** Keys an operator can set: adjustable on at least one deployment. */
const helmKeys = FEATURE_KEYS.filter((key) => featureIsAdjustable(key, "self_hosted") || featureIsAdjustable(key, "cloud"))

function defaultLabel(key) {
  const selfHosted = featureAvailability(key, "self_hosted")
  const availability = typeof selfHosted === "object" ? selfHosted : featureAvailability(key, "cloud")
  const scope = featureIsAdjustable(key, "self_hosted") ? "" : " (cloud only)"
  return `default ${availability.default ? "on" : "off"}${scope}`
}

function valuesBlock() {
  const width = Math.max(...helmKeys.map((key) => key.length)) + 5
  const lines = [
    `  ${BEGIN}`,
    "  # Per-feature switches for this deployment. Each key renders DEN_FEATURE_<KEY>.",
    "  # Only features platform admins can change per organization appear here.",
    "  #   \"\"      use the default below; platform admins can change it per organization in /admin",
    "  #   \"true\"  on for every organization; /admin shows \"Set by deployment config\"",
    "  #   \"false\" off for every organization; /admin shows \"Set by deployment config\"",
    "  features:",
    ...helmKeys.map((key) => `    ${`${key}: ""`.padEnd(width)}# ${defaultLabel(key)} · ${FEATURES[key].description}`),
    `  ${END}`,
  ]
  return lines.join("\n")
}

function renderValues(current) {
  const start = current.indexOf(`  ${BEGIN}`)
  const end = current.indexOf(`  ${END}`)
  if (start === -1 || end === -1) {
    throw new Error(`${path.relative(root, valuesPath)} is missing the generated features markers.`)
  }
  return current.slice(0, start) + valuesBlock() + current.slice(end + `  ${END}`.length)
}

function renderSchema() {
  const schema = {
    $schema: "http://json-schema.org/draft-07/schema#",
    $comment: "Generated by pnpm features:sync from packages/features/src/registry.ts. Only config.deployment and config.features are constrained.",
    type: "object",
    properties: {
      config: {
        type: "object",
        properties: {
          deployment: {
            type: "string",
            enum: ["cloud", "self_hosted"],
            description: "Which product this install is. Only OpenWork Cloud sets \"cloud\". Renders DEN_DEPLOYMENT.",
          },
          features: {
            type: "object",
            additionalProperties: false,
            properties: Object.fromEntries(helmKeys.map((key) => [key, {
              // --set turns "true" into a boolean, so accept both spellings.
              enum: ["", "true", "false", true, false],
              description: `${FEATURES[key].label}: ${FEATURES[key].description} Renders ${featureLockEnvName(key)}.`,
            }])),
          },
        },
      },
    },
  }
  return `${JSON.stringify(schema, null, 2)}\n`
}

function renderReadme(current) {
  const start = current.indexOf(README_BEGIN)
  const end = current.indexOf(README_END)
  if (start === -1 || end === -1) {
    throw new Error(`${path.relative(root, readmePath)} is missing the generated features markers.`)
  }
  const rows = helmKeys.map((key) => `| \`${key}\` | \`${featureLockEnvName(key)}\` | ${defaultLabel(key)} | ${FEATURES[key].description} |`)
  const table = [
    README_BEGIN,
    "| `config.features.*` | Environment variable | Default | What it does |",
    "| --- | --- | --- | --- |",
    ...rows,
    README_END,
  ].join("\n")
  return current.slice(0, start) + table + current.slice(end + README_END.length)
}

const problems = []

function compareOrWrite(filePath, next) {
  const current = readFileSync(filePath, "utf8").toString()
  if (current === next) return
  if (check) problems.push(`${path.relative(root, filePath)} is out of date. Run \`pnpm features:sync\` and commit the result.`)
  else writeFileSync(filePath, next)
}

compareOrWrite(valuesPath, renderValues(readFileSync(valuesPath, "utf8")))
compareOrWrite(readmePath, renderReadme(readFileSync(readmePath, "utf8")))
let schemaCurrent = ""
try {
  schemaCurrent = readFileSync(schemaPath, "utf8")
} catch {
  schemaCurrent = ""
}
if (schemaCurrent !== renderSchema()) {
  if (check) problems.push(`${path.relative(root, schemaPath)} is out of date. Run \`pnpm features:sync\` and commit the result.`)
  else writeFileSync(schemaPath, renderSchema())
}

if (check) {
  // Registry rules.
  const now = new Date()
  for (const key of FEATURE_KEYS) {
    const definition = FEATURES[key]
    if (!/^[a-z][a-z0-9]*(?:[A-Z][a-z0-9]+)*$/.test(key)) {
      problems.push(`Feature key "${key}" must be lowerCamelCase with no consecutive capitals (it becomes ${featureLockEnvName(key)}).`)
    }
    if (!definition.label.trim() || !definition.description.trim()) problems.push(`Feature "${key}" needs a label and a description.`)
    const since = /^(\d{4})-(\d{2})$/.exec(definition.since)
    if (!since) {
      problems.push(`Feature "${key}" since must be "YYYY-MM".`)
      continue
    }
    const ageMonths = (now.getUTCFullYear() - Number(since[1])) * 12 + (now.getUTCMonth() + 1 - Number(since[2]))
    const fixed = [definition.cloud, definition.selfHosted].every((value) => value === "on" || value === "off" || value === "unavailable")
    const dead = [definition.cloud, definition.selfHosted].every((value) => value === "off" || value === "unavailable")
    const shipped = [definition.cloud, definition.selfHosted].every((value) => value === "on" || value === "unavailable")
    if (fixed && (dead || shipped) && ageMonths > 6) {
      problems.push(`Feature "${key}" has been fixed ${shipped ? "on" : "off"} everywhere since ${definition.since}. Delete the flag and its checks (see .opencode/skills/add-a-feature).`)
    }
  }

  // The chart must render exactly the variable names den-api reads.
  let helmAvailable = true
  try {
    execFileSync("helm", ["version", "--short"], { stdio: "ignore" })
  } catch {
    helmAvailable = false
  }
  const chartStale = problems.some((problem) => problem.includes("out of date"))
  if (helmAvailable && !chartStale) {
    const setArgs = helmKeys.flatMap((key) => ["--set-string", `config.features.${key}=true`])
    let rendered = ""
    try {
      rendered = execFileSync("helm", ["template", "features-check", chartDir, "--show-only", "templates/configmap.yaml", ...setArgs], { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] })
    } catch (error) {
      const stderr = error && typeof error === "object" && "stderr" in error ? String(error.stderr) : String(error)
      problems.push(`helm template failed with every feature key set: ${stderr.trim()}`)
    }
    const renderedNames = new Set([...rendered.matchAll(/^\s+(DEN_FEATURE_[A-Z0-9_]+):/gm)].map((match) => match[1]))
    for (const key of helmKeys) {
      if (!renderedNames.has(featureLockEnvName(key))) {
        problems.push(`Helm renders no ${featureLockEnvName(key)} for config.features.${key}; den-api would never see it.`)
      }
    }
    for (const name of renderedNames) {
      if (!helmKeys.some((key) => featureLockEnvName(key) === name)) problems.push(`Helm renders ${name}, which den-api does not read.`)
    }
    if (!/^\s+DEN_DEPLOYMENT: "self_hosted"$/m.test(rendered)) problems.push("Helm must render DEN_DEPLOYMENT, defaulting to self_hosted.")
  } else if (!helmAvailable) {
    console.warn("[features] helm is not installed; skipped the chart render check.")
  }

  // No new deployment-wide feature switches: declare a feature instead.
  const allowedEnableFlags = new Set([
    "DEN_APP_MCP_SERVERS_ENABLED", "DEN_AUDIT_CAPTURE_ENABLED", "DEN_AUDIT_SELF_HOSTED_ENABLED", "DEN_AUDIT_VISIBILITY_ENABLED",
    "DEN_AUTOMATIONS_ENABLED", "DEN_AUTOMATIONS_RUNTIME_ENABLED", "DEN_BOTID_PROTECTION_ENABLED", "DEN_DASHBOARDS_ENABLED",
    "DEN_GENERATED_ARTIFACT_VIEWS_ENABLED", "DEN_OPENWORK_WEB_ENABLED", "DEN_PASSWORD_BREACH_SCREENING_ENABLED",
    "DEN_PLAN_GATING_ENABLED", "DEN_SLACK_ASSISTANT_WORKER_ENABLED",
  ])

  function* sourceFiles(dir) {
    for (const entry of readdirSync(dir)) {
      if (entry === "node_modules" || entry === "dist" || entry === ".next" || entry === "drizzle" || entry === "gen") continue
      const full = path.join(dir, entry)
      if (statSync(full).isDirectory()) yield* sourceFiles(full)
      else if (/\.(ts|tsx|mjs)$/.test(entry)) yield full
    }
  }

  // Feature overrides live in the organization_feature table; only the store
  // (and the one-release rollback copy) may touch metadata.capabilities.
  const metadataCapabilitiesAllowed = new Set([
    "ee/packages/den-db/src/organization-features.ts",
    "ee/apps/den-api/src/orgs.ts",
  ])

  for (const dir of ["ee/apps/den-api/src", "ee/apps/den-web/app", "ee/apps/den-web/components", "ee/apps/gateway/src", "ee/packages", "apps/app/src", "apps/server/src"]) {
    const absolute = path.join(root, dir)
    try {
      statSync(absolute)
    } catch {
      continue
    }
    for (const file of sourceFiles(absolute)) {
      const relative = path.relative(root, file)
      const text = readFileSync(file, "utf8")
      if (relative.startsWith("ee/apps/den-api/src")) {
        for (const match of text.matchAll(/\bDEN_[A-Z0-9_]+_ENABLED\b/g)) {
          if (!allowedEnableFlags.has(match[0])) {
            problems.push(`${relative}: new switch ${match[0]}. Declare a feature in packages/features/src/registry.ts instead (see .opencode/skills/add-a-feature).`)
          }
        }
      }
      if (!metadataCapabilitiesAllowed.has(relative) && /metadata\)?\??\.capabilities\b|\$\.capabilities/.test(text)) {
        problems.push(`${relative}: reads organization metadata.capabilities. Use getOrganizationFeatures() / orgFeatureEnabled() instead.`)
      }
    }
  }
}

if (problems.length > 0) {
  for (const problem of [...new Set(problems)]) console.error(`[features] ${problem}`)
  process.exit(1)
}
console.log(check ? "[features] Registry, Helm chart and guard rules are in sync." : "[features] Helm chart files regenerated.")
