import type { UiArtifactPayload } from "@openwork/types/ui-artifact"

export const CALENDAR_EXAMPLE = {
  artifactId: "calendar.view",
  instanceId: "demo-calendar-2026-07-23",
  revision: 1,
  operation: "create",
  title: "Today at a glance",
  subtitle: "Thursday, July 23",
  presentation: { placement: "inline", size: "standard" },
  source: {
    type: "mock",
    label: "UI Artifacts demo",
    provider: "Google Calendar",
    account: "alex@example.com",
    observedAt: "2026-07-23T08:30:00+02:00",
  },
  data: {
    variant: "day",
    startDate: "2026-07-23",
    endDate: "2026-07-23",
    timezone: "Europe/Berlin",
    events: [
      {
        id: "architecture-review",
        title: "Architecture review",
        start: "2026-07-23T09:30:00+02:00",
        end: "2026-07-23T10:15:00+02:00",
        location: "Conference room A",
        calendar: "Work",
        status: "confirmed",
        action: {
          id: "open-architecture-review",
          label: "View event",
          type: "open_url",
          url: "https://calendar.google.com/calendar/u/0/r/day",
        },
      },
      {
        id: "product-sync",
        title: "Product sync",
        start: "2026-07-23T11:00:00+02:00",
        end: "2026-07-23T11:45:00+02:00",
        location: "Microsoft Teams",
        calendar: "Work",
        status: "confirmed",
      },
      {
        id: "customer-call",
        title: "Customer call",
        start: "2026-07-23T13:30:00+02:00",
        end: "2026-07-23T14:00:00+02:00",
        location: "Zoom",
        calendar: "Work",
        status: "confirmed",
      },
      {
        id: "performance-check-in",
        title: "Performance check-in",
        start: "2026-07-23T15:00:00+02:00",
        end: "2026-07-23T15:30:00+02:00",
        location: "Workday",
        calendar: "Work",
        status: "tentative",
      },
    ],
    focusWindow: {
      start: "2026-07-23T16:00:00+02:00",
      end: "2026-07-23T18:30:00+02:00",
      label: "Best focus window",
    },
    action: {
      id: "open-calendar",
      label: "Open calendar",
      type: "open_url",
      url: "https://calendar.google.com/calendar/u/0/r/day",
    },
  },
} satisfies UiArtifactPayload

export const COMMUNICATION_THREAD_EXAMPLE = {
  artifactId: "communication.thread",
  instanceId: "demo-slack-launch-thread",
  revision: 1,
  operation: "create",
  title: "Launch readiness thread",
  subtitle: "#product-launch",
  presentation: { placement: "inline", size: "standard" },
  source: {
    type: "mock",
    label: "UI Artifacts demo",
    provider: "Slack",
    account: "Acme workspace",
    observedAt: "2026-07-23T10:04:00+02:00",
  },
  data: {
    workspace: "Acme",
    channel: "product-launch",
    topic: "Final checks for the desktop release",
    unreadCount: 3,
    messages: [
      {
        id: "slack-1",
        author: "Maya Chen",
        timestamp: "2026-07-23T09:48:00+02:00",
        body: "The release candidate is signed and the macOS smoke check is green.",
        reactions: [{ emoji: "✅", count: 4 }],
      },
      {
        id: "slack-2",
        author: "Theo Martin",
        timestamp: "2026-07-23T09:56:00+02:00",
        body: "Windows validation is still running. I will post the result before the go/no-go.",
        reactions: [{ emoji: "👀", count: 2 }],
      },
      {
        id: "slack-3",
        author: "Priya Shah",
        timestamp: "2026-07-23T10:03:00+02:00",
        body: "Docs and customer messaging are ready. No remaining content blockers.",
      },
    ],
    action: {
      id: "open-slack",
      label: "Open Slack",
      type: "open_url",
      url: "https://app.slack.com/client",
    },
  },
} satisfies UiArtifactPayload

export const MAIL_INBOX_EXAMPLE = {
  artifactId: "mail.inbox",
  instanceId: "demo-gmail-priority-inbox",
  revision: 1,
  operation: "create",
  title: "Priority inbox",
  subtitle: "Messages likely needing a reply",
  presentation: { placement: "inline", size: "standard" },
  source: {
    type: "mock",
    label: "UI Artifacts demo",
    provider: "Gmail",
    account: "alex@example.com",
    observedAt: "2026-07-23T10:10:00+02:00",
  },
  data: {
    account: "alex@example.com",
    folder: "Inbox",
    unreadCount: 3,
    messages: [
      {
        id: "mail-1",
        sender: "Jordan Lee",
        senderEmail: "jordan@example.com",
        subject: "Decision needed: launch window",
        snippet: "Can you confirm whether we are keeping the 16:00 rollout window?",
        receivedAt: "2026-07-23T09:58:00+02:00",
        unread: true,
        labels: ["Important", "Launch"],
        action: {
          id: "open-mail-1",
          label: "Open",
          type: "open_url",
          url: "https://mail.google.com/mail/u/0/#inbox",
        },
      },
      {
        id: "mail-2",
        sender: "Finance Ops",
        senderEmail: "finance@example.com",
        subject: "Expense report returned",
        snippet: "One receipt needs a project code before the report can be approved.",
        receivedAt: "2026-07-23T08:41:00+02:00",
        unread: true,
        labels: ["Finance"],
      },
      {
        id: "mail-3",
        sender: "Customer Success",
        senderEmail: "success@example.com",
        subject: "Notes from the Acme call",
        snippet: "The customer confirmed the pilot scope and asked for a follow-up next week.",
        receivedAt: "2026-07-22T17:22:00+02:00",
        unread: false,
        labels: ["Customer"],
      },
    ],
    action: {
      id: "open-gmail",
      label: "View inbox",
      type: "open_url",
      url: "https://mail.google.com/mail/u/0/#inbox",
    },
  },
} satisfies UiArtifactPayload

export const ATTENTION_EXAMPLE = {
  artifactId: "work.attention",
  instanceId: "demo-attention-queue",
  revision: 1,
  operation: "create",
  title: "Needs your attention",
  subtitle: "Four items across your connected work",
  presentation: { placement: "inline", size: "standard" },
  source: {
    type: "mock",
    label: "UI Artifacts demo",
    provider: "OpenWork Connect",
    observedAt: "2026-07-23T10:12:00+02:00",
  },
  data: {
    items: [
      {
        id: "incident-payment-latency",
        kind: "incident",
        title: "P1 payment latency",
        description: "Payment service p95 latency is above the incident threshold.",
        priority: "critical",
        source: "ServiceNow",
        dueAt: "2026-07-23T10:30:00+02:00",
      },
      {
        id: "approval-payroll",
        kind: "approval",
        title: "Payroll declaration",
        description: "Submit the declaration before the July close.",
        priority: "high",
        source: "Workday",
        dueAt: "2026-07-31T17:00:00+02:00",
      },
      {
        id: "training-security",
        kind: "learning",
        title: "Security training due",
        description: "Complete the annual security refresher.",
        priority: "normal",
        source: "Learning",
        dueAt: "2026-07-24T17:00:00+02:00",
      },
      {
        id: "goal-update",
        kind: "goal",
        title: "Goal update requested",
        description: "Your manager requested a progress update.",
        priority: "normal",
        source: "Goals",
      },
    ],
  },
} satisfies UiArtifactPayload

export const WIDGETS_EXAMPLE = {
  artifactId: "widgets.collection",
  instanceId: "demo-work-widgets",
  revision: 1,
  operation: "create",
  title: "Your widgets",
  subtitle: "A combined view across your connected work",
  presentation: { placement: "inline", size: "standard" },
  source: {
    type: "mock",
    label: "UI Artifacts demo",
    provider: "OpenWork Connect",
    observedAt: "2026-07-23T10:15:00+02:00",
  },
  data: {
    layout: "grid",
    widgets: [
      {
        id: "meetings",
        kind: "metric",
        label: "Meetings",
        value: "4",
        detail: "Today",
        tone: "info",
        trend: { direction: "flat", label: "Same as yesterday" },
      },
      {
        id: "goals",
        kind: "progress",
        label: "Q3 goals",
        value: "72%",
        detail: "On track",
        progress: 72,
        tone: "success",
      },
      {
        id: "incident",
        kind: "status",
        label: "Payment service",
        value: "Needs attention",
        detail: "P1 latency incident",
        status: "attention",
        tone: "critical",
      },
      {
        id: "leave",
        kind: "balance",
        label: "Leave balance",
        value: "14",
        unit: "days",
        detail: "Available",
        tone: "success",
      },
      {
        id: "payroll",
        kind: "date",
        label: "Next payslip",
        value: "Jul 31",
        timestamp: "2026-07-31T09:00:00+02:00",
        detail: "8 days",
        tone: "neutral",
      },
      {
        id: "learning",
        kind: "progress",
        label: "Learning",
        value: "2 of 5",
        detail: "Courses in progress",
        progress: 40,
        tone: "info",
      },
    ],
  },
} satisfies UiArtifactPayload

export const APPROVALS_EXAMPLE = {
  artifactId: "work.approvals",
  instanceId: "demo-approval-queue",
  revision: 1,
  operation: "create",
  title: "Approvals",
  subtitle: "Decisions waiting for you",
  presentation: { placement: "inline", size: "standard" },
  source: {
    type: "mock",
    label: "UI Artifacts demo",
    provider: "OpenWork mock approvals",
    observedAt: "2026-07-23T10:18:00+02:00",
  },
  data: {
    items: [
      {
        id: "expense-lisbon",
        title: "Customer workshop travel",
        description: "Flights and two hotel nights for the Acme customer workshop in Lisbon.",
        requestor: "Maya Chen",
        submittedAt: "2026-07-23T08:42:00+02:00",
        dueAt: "2026-07-24T17:00:00+02:00",
        amount: "€1,280",
        source: "Workday",
        status: "pending",
        actions: [
          {
            id: "approve-expense-lisbon",
            label: "Approve",
            type: "request_decision",
            instanceId: "demo-approval-queue",
            itemId: "expense-lisbon",
            decision: "approve",
            expectedRevision: 1,
            description: "Stage approval through the agent",
          },
          {
            id: "reject-expense-lisbon",
            label: "Reject",
            type: "request_decision",
            instanceId: "demo-approval-queue",
            itemId: "expense-lisbon",
            decision: "reject",
            expectedRevision: 1,
            description: "Stage rejection through the agent",
          },
        ],
      },
      {
        id: "access-production",
        title: "Production dashboard access",
        description: "Read-only access for the support rotation.",
        requestor: "Theo Martin",
        submittedAt: "2026-07-23T09:16:00+02:00",
        source: "ServiceNow",
        status: "pending",
        actions: [
          {
            id: "approve-access-production",
            label: "Approve",
            type: "request_decision",
            instanceId: "demo-approval-queue",
            itemId: "access-production",
            decision: "approve",
            expectedRevision: 1,
          },
          {
            id: "reject-access-production",
            label: "Reject",
            type: "request_decision",
            instanceId: "demo-approval-queue",
            itemId: "access-production",
            decision: "reject",
            expectedRevision: 1,
          },
        ],
      },
    ],
  },
} satisfies UiArtifactPayload

export const WORKSPACE_BRIEF_EXAMPLE = {
  artifactId: "workspace.brief",
  instanceId: "demo-workspace-brief",
  revision: 1,
  operation: "create",
  title: "Good morning, Alex",
  subtitle: "Here is what is happening across your work today",
  presentation: { placement: "inline", size: "expanded" },
  source: {
    type: "mock",
    label: "UI Artifacts demo",
    provider: "OpenWork Connect",
    observedAt: "2026-07-23T10:20:00+02:00",
  },
  data: {
    summary: "You have four meetings, three messages likely needing a reply, one critical incident, and two approvals waiting.",
    metrics: [
      { id: "meetings", label: "Meetings", value: "4", detail: "Today", tone: "info" },
      { id: "replies", label: "Replies", value: "3", detail: "Need response", tone: "warning" },
      { id: "tasks", label: "Tasks", value: "5", detail: "Due today", tone: "success" },
      { id: "critical", label: "Critical", value: "1", detail: "P1 incident", tone: "critical" },
    ],
    schedule: CALENDAR_EXAMPLE.data.events,
    attention: ATTENTION_EXAMPLE.data.items,
    progress: [
      { id: "goals", label: "Q3 goals", value: "72%", detail: "On track", progress: 72, tone: "success" },
      { id: "learning", label: "Learning", value: "2 of 5", detail: "Courses in progress", progress: 40, tone: "info" },
      { id: "payroll", label: "Next payslip", value: "Jul 31", detail: "8 days", tone: "neutral" },
      { id: "leave", label: "Leave balance", value: "14 days", detail: "Available", tone: "success" },
    ],
    quickActions: [
      {
        id: "open-calendar",
        label: "Open calendar",
        type: "open_url",
        url: "https://calendar.google.com/calendar/u/0/r/day",
      },
      {
        id: "open-inbox",
        label: "Open inbox",
        type: "open_url",
        url: "https://mail.google.com/mail/u/0/#inbox",
      },
      {
        id: "open-slack",
        label: "Open Slack",
        type: "open_url",
        url: "https://app.slack.com/client",
      },
    ],
  },
} satisfies UiArtifactPayload

export const UI_ARTIFACT_EXAMPLES = [
  WORKSPACE_BRIEF_EXAMPLE,
  CALENDAR_EXAMPLE,
  WIDGETS_EXAMPLE,
  COMMUNICATION_THREAD_EXAMPLE,
  MAIL_INBOX_EXAMPLE,
  ATTENTION_EXAMPLE,
  APPROVALS_EXAMPLE,
] satisfies readonly UiArtifactPayload[]
